var unidad1 = ["Here we are in school again.",
"It's great to be with all my friends.",
"Hello and how are you?|I'm very well, thanks.|How about you?",
"Lots of fantastic things to do.",
"Reading, writing and playing too.",
"Lots of fantastic things to see.",
"I have all my friends with me.",
"What's your name?|I'm Rachel.",
"What's your favorite sport?|I like swimming.",
"Do you have pets?|Yes, I have a cat.",
"How old are you?|That's a secret.",
"I spy with my little eye.",
"I'm  watching something beginning with en.",
"Is it a nose?|No, it isn't.|Please guess again.",
"I spy with my little eye.",
"I'm  watching something beginning with c.",
"Is it chocolate?|Yes, it is.",
"Now spell the word with me.",
"How do you spell plane?",
"The TV is broken.",
"Is it five o'clock?No, it's three thirty.",
"What time is it?|It's four o'clock.",
"What time is it now?|It's four thirty.",
"Don't worry.|There's a lot of time.",
"It's five o'clock.|It's time for my favorite show.",
"Hurry up.|It's time for school.",
"Don't be late.",
"School is cool.",
"We love music and science.",
"So many things to learn and do.",
"I love math.",
"I like speaking spanish.",
"I love music.",
"Do you like math?|Yes, I love math.",
"Do you like speaking spanish?|Yes, I do.",
"Do you like music?|Yes, I do.",
"Do you like science?|Yes, I do.",
"Do you like art?|Yes, I do.",
"Hello, Dan.|What do you have today?|It's monday.|I have science.",
"Do you have music?|No, I don't.|I have music on friday.|Me too.",
"What do you have today, Olga?|I have english and science.",
"Do you have math?|Yes, at nine o'clock.|Look, it's nine o'clock now.",
"What do you have today?It's thursday.|I have math, english and art,",
"Hi, my name's Alice.",
"My favorite day is thursday.",
"In the morning, I have Spanish and music.",
"Math is my favorite subject.",
"I like playing games and writing stories on the computer.",
"In music class, I like playing the guitar.",
"In the afternoon, I have science.",
"I like studying plants and science class.",
"After school on Thursday, I go to the swimming club with my friends.",
"Thursday is a fantastic day.",
"Alice's favorite day is Tuesday.",
"Her favorite subject is math.",
"She has music in the afternoon.",
"She doesn't like playing the guitar.",
"She likes studying plants.",
"After school, she goes to tennis club.",
"It's nine thirty and Karim is late for school.|The principal isn't happy.",
"You have math now.|Hurry up.",
"The children aren't in the classroom.|Do we have science today?",
"Karim class isn't in the gym.|He doesn't have sport today?",
"Where is my class?|Look in the music room.",
"Karim is in the music room.",
"There are children playing and recording.",
"Where is my class?|Your class is in the library.",
"Karim is in the library.|There are a lots of books.",
"You have science now.|Go to the computer room.",
"Karim goes to the computer room.|But they aren't there.",
"I can't find my class.|Your class is on the playground.",
"It's time for the class photo.|Look at the big camera.",
"Karim shows the photo to his mom.|She doesn't like it.",
"Mom, here's the class photo.",
"Here's our classroom.|Can you see?",
"We're learning math.|My friends and mee.",
"In the gym we jump and climb.",
"We all have a fantastic time.",
"In the library, there are books.",
"Come with me and take a look.",
"The cafeteria is where we meet.",
"When it's time for us to eat.",
"My favorite subject is science.",
"The computer room's the place for me.",
"We go to the playground every day.|To see our friends and run and play.",
"You can't run or jump here.|You can read books.|Where am I?|You're in the library.",
"I'm Kate.|Look at the photos of the playground at my school.",
"We have a games area.|You can run and jump here.",
"This is the quiet area.|We read books and talk with our friends here.",
"We have a sports area.|You can play basketball, soccer and table tennis here.",
"This is our jungle gym.|Climbing's difficult for me, but I like it.",
"They are the new school librarians.",
"I have music next.|Can I have a songbook?",
"He is looking for songbooks.",
"This isn't the music section.",
"I have English homework today.",
"Follow me to the English section.",
"Do you have an English dictionary|Yes, they're on the top shelf.",
"Be quiet.|This is a library."];

var unidad2 = ["Do you know the countries?",
"Sing along with me.",
"Can you find them on the map?",
"How many countries can you see?",
"Ireland, France and the United Kingdom.",
"And over there, is the United States of America.",
"Can you point to Mexico?",
"How many countries do you know?",
"China, Italy and Spain.",
"Let's sing the countries song.",
"How do you go to Mexico?",
"HI, my name is Karim.|Hello, I'm Tania.",
"Where are you from?|I'm from Italy.",
"Do you like skateboarding?|Yes, it's my favorite sport.",
"He's skateboarding with his hands.|He's fantastic.",
"Where's he from?|He's from the USA.",
"Look at that girl.|She's jumping.",
"That's Rosie.|She's from Ireland.|She's great.",
"Where are you from?|I'm from the UK.",
"How old are you ?|I'm nine.",
"Are you Laura?|Yes, I am.",
"Where are you from?|I'm from Mexico.",
"How old are you ?|I'm ten.",
"Are you Lucia?|No, I'm not.",
"My name is Nico.|I'm from Italy|I speak italian and english.",
"I'm Marta.|I'm from Spain.|I speak spanish and english.",
"My name is Jia.|I'm from China.|I speak chinese and english.",
"I'm Piere.|I'm from France.|I speak french and english.",
"Hello friends.|My name's Sam.|I'm nine years old.",
"I'm from the USA.|I speak english and spanish.",
"My hobbies are swimming and playing the guitar.",
"Please write to me.",
"Hi.|My name's Alicia.|I'm eight years old.",
"I'm from Mexico.|I speak english and spanish.",
"My hobbies are listening to music and writing to my friends.",
"Please write to me.",
"Lucy likes listening to music and dancing.",
"Her favorite singer is Paulina.|Paulina is from Mexico.|She's very smart.",
"She can speak spanish, english and french.",
"Paulina is singing on saturday.|Tom doesn't like Paulina.",
"Can we go to the concert, Dad?",
"Everybody likes Paulina.|There are no tickets left.",
"Sorry, Lucy.|We can't go to the concert.",
"Lucy is very sand.|She wants to go to the concert.",
"Look at that car.|That's Alberto.|He plays the guitar in Paulina's band.",
"Hello.|Can I help?Yes, please.",
"Pierre is from France.|He speaks french and spanish.|He doesn't speak english.",
"Dad helps fix the car.",
"Look, Lucy.|It's Paulina.|Hello.",
"Here are three tickets for my concert.|Thanks.",
"Now we can go to the concert.|Thank you.",
"And thank you to Lucy and Tom.",
"Paul is from France.|He likes painting and swimming at the sea.",
"Flor likes skiing and singing songs.|She's from Italy.",
"Ling is from China.|She likes cycling and reading comics.",
"Marco likes dancing.|He's from Spain.|What about you?",
"Tara is from Irelan.|She likes listening to music.",
"Roberto is from México.|He likes playing basketball.",
"Lorna is from UK.|She likes taking photos.",
"Mac is from the USA.|He likes surfing.",
"China is a big country in Asia.",
"The capital city is Beijing.",
"The chinese flag is red with five yellow stars.",
"Kites, firework and paper are chinese inventions.",
"Table tennis and gymnastics are popular sports in China.",
"Brazil is a big country, too.|It's in South America.",
"Brasilia is the capital city.",
"The brazilian flag is green, blue and yellow.",
"You can visit the Amazon rain forest in Brasil.",
"Jaguars and parrots live there.",
"Soccer and volleyball are popular sports in Brazil.",
"What's the capital city fo the USA?|It's Washington DC.",
"What's the capital of China?|It's Beijing.",
"What color is the spanish flag?|It's red and yellow.",
"What color is the french flag?|It's blue, white and red.",
"They are at an international food festival.",
"Come on.|I'm hungry.|Me too.",
"I love eating cheese.|Do you speak english?|Yes, I do.",
"This spaghetti is from Italy.|I don't like spaghetti.",
"What are these?|Be careful.|They're chilies.",
"He doesn't like chilies.",
"Here's some ice cream from Italy.|Thank you."];

var unidad3 = ["January.",
"February.",
"March.",
"April.",
"May.",
"June.",
"July.",
"August.",
"September.",
"October.",
"November.",
"December.",
"The first three months of the year.",
"Sunny days are here.",
"Back to school with books and pens.",
"Another year begins again.",
"When's your birthday?|It's in February.",
"My birthday's in November.",
"Olga's cousin is visiting for Christmas.",
"His name's Ricky and he's from Australia.",
"Hi, Ricky.|Do you like Christmas?|Yes, I do.",
"In Australia it's hot and sunny on Christmas.",
"What do you wear on Christmas?|I wear shorts and a T-shirts.",
"I wear a sweater on Christmas.",
"What do you eat?|My family has a big barbecue.",
"I eat hot dogs and salad.",
"I don't eat salad on Christmas.",
"I eat turkey, vegetables and potatoes.",
"Where do you go?|I go to the beach with my family.",
"I swim in the ocean.",
"I want to go to Australia for Christmas.",
"It's fantastic.",
"What do you wear in January?|I wear a sweater and a coat.",
"What do you wear in july?|I wear shorts and T-shirts in the summer.",
"Where do you go in August?|We go to the beach with my family.",
"Where do you go in December?|We go ski resorts to play with snow.",
"What do you eat on Christmas?We eat roasted turkey and mashed potatoes.",
"What do you eat on June?|We eat fruits, such as strawberries, raspberries and blueberries.",
"In February we play with kites.",
"In July we go to the beach.",
"In October we celebrate hallowing.",
"In December we celebrate Christmas.",
"In January, I wear a T-shirt.",
"In February, I swim in the ocean.",
"In March, I go the the park.",
"In April, I ride my bike.",
"In May, I wear a sweater.",
"In June, I eat strawberries.",
"In July, I wear shorts.",
"In August, we go the beach.",
"In September, we go to school.",
"In November, I wear a hat.",
"In December, I eat ice cream.",
"In January, I don't wear a T-shirt.",
"In January, I wear a T-shirt in the gym.",
"Hi Mon.|It's winter here.|It's snowing.",
"It's very hot here today.|I don't like summer.",
"He is talking to his family in Australia on the computer.",
"It's summer in Australia.",
"The children are going ice-skating in the park.",
"I like your skates, Tom.",
"Ricky, don't forget your scarf.",
"Olga, don't forget the hot chocolate.",
"Tom wants to scare Ricky.",
"Look at the footprints.",
"It's a snow monster.",
"They are very big.",
"Be careful, Ricky.",
"Ice-skating is difficult.",
"Lucy and Olga are having fun.|But Karim doesn't like ice-skating.",
"Now, it's snowing.",
"Look, there's a shelter.|Let's go.",
"I don't like winter.|It's cold.",
"Where's the hot chocolate.|It's at home.",
"It's the snow monster.|Dat, it's you.",
"He's trying to scary him.",
"Let's have hot chocolate.",
"Tom is scared of snow monsters.",
"Seasons come, seasons go.",
"Some bring rain and some bring snow.",
"Some bring wind and some bring sun.",
"Which is your favorite one?",
"In the spring, there's a lot of rain.",
"All the flowers come out again.",
"In the summer, there's no school.",
"We go swimming in the pool.",
"In autumn, all the leaves fall down.",
"Red and yellow, orange and brown.",
"In winter, when the cold winds blow.",
"We go skiing in the snow.",
"I'm Tessa.|My favorite season is spring.",
"I like flowers and baby animals.",
"I wear a jacket and pants.",
"I ride my bike in the park.",
"I eat chocolate eggs at easter.",
"I'm Max.|My favorite season is autumn.",
"I like the red and yellow leaves.",
"I wear a hat and a coat.",
"I play soccer with my friends.",
"I eat grapes and apples.",
"In summer, it's hot and bears like swimming in cold rivers and lakes.",
"In Autumn, bears find a cave or make a den for winter.",
"They eat a lot and they grow more fur.",
"In winter, it's cold and brown bears sleep in a cave or in a den.",
"They don't eat or drink for three months.",
"Brown bears wake up in spring.",
"They are very hungry and eat a lot.",
"They eat plants, insects and fish.",
"Brown bears live in Spain, the USA, Russia and other countries.",
"In Spain, they are endangered species.",
"Brown bears stand on two legs to find food.",
"They are two meters tall.",
"Brown bears like to eat honey.",
"It's January and it's snowing.",
"I don't like the winter.",
"What is he doing?|Why is he painting the wall?",
"When it's summer, I go to the beach.",
"I wear shorts and sunglasses in summer.",
"He has tanning bed.",
"What are you doing?|it's a surprise.",
"It's very sunny in summer too.",
"Now, it's summer.|They are at the beach.",
"Thanks you.|I like your surprise."];

var maxUnidades = 3;
