var unidad1 = [
"I'm Tom.|I'm eight.|How about you?",
"I'm Olga.|I'm nine.|Nice to meet you.",
"I'm Mark.|How old are you?|I'm nine.",
"How many boats can you see?|I see twelve boats.",
"Come on Jhon, count with me.",
"Orange, yellow, green and blue.",
"I'm ready for school.|Yes, school is cool.",
"I have my big Schoolbag.|And my sharpener too.",
"I have my books and my pencils.|How about you?",
"I have my favorite ruler.|An my pencil case.",
"I have my pen and my eraser.|And a smile on my face.",
"The pencil case is yellow.",
"The pencil is red.",
"The book is blue.",
"The ruler is green.",
"The pen is black.",
"The sharpener is red.",
"The schoolbag is purple.",
"The eraser is pink and red.",
"Hello Karim.|Hi Lucy.",
"Do you have a pencil?|Yes, I do.|Here you are.",
"Do you have an eraser?|Yes, I do.",
"Thanks. Do you have a ruler?|No. I don't. Sorry.",
"Do you like my picture?|Yes. It's very interesting.",
"Do you have a blue pen?|Yes, I do.",
"Do you have a blue pencil case?|No. I don't.",
"Do you have a blue schoolbag?No. I have a pink and black schoolbag.",
"The children are at the zoo.|They're drawing the monkeys.",
"Tom likes this monkey.",
"Hurry up, Tom.",
"Let's go and see the crocodiles.",
"Tom leaves his hat and coat on the chair.",
"Tom leaves his bag under the trash can.",
"What is the monkey doing?",
"The monkey is putting on Tom's jacket and hat.",
"The monkey has Tom's schoolbag.",
"Tom isn't drawing and the teacher isn't happy.",
"Look at the monkey.",
"I don't have my schoolbag.",
"Now the children are in the snake house.",
"Look at the monkey, Tom.|It's behind you.",
"It's time for lunch.",
"I have sandwiches.",
"I have fruit and yogurt.",
"Tom. Come down now.",
"The monkey has Tom's lunch box.",
"The teacher is very angry now.",
"Look behind you, monkey.",
"Look, monkey.|I have a banana.",
"The monkey is in the cage again.|It's time to go back to school.",
"Good bye, monkey.",
"Tom, where are your sunglasses?",
"Where's the book?|Look and find.",
"In, on, under or behind.",
"There it is.|I can see.",
"It's under the table.",
"Where's the ruler?|It's in the schoolbag.",
"Where's the ball?|It's on the chair.",
"Can I have four boxes of colored pencils, please?|Yes, follow me.",
"Robby is helping Beep in the stationery store.",
"And can I have two electric sharpeners?|Yes, they're on the table.",
"And three pencil cases and six erasers.|Here you are.",
"And four, five, six erasers.",
"And fourteen blue pens, eleven black pens and five rulers.",
"And five rulers.|And a schoolbag, please.",
"Be careful, Robby.",
"Robby, the very big schoolbags are behind you.",
"Pink and purple pencils.",
"Pens and pencil cases.",
"Peter and Patricia.",
"Drawing funny faces."
];


var maxUnidades = 1;
