var unidad1 = [
"There are two eggs.",
"There are three toasts.",
"There is a glass of milk.",
"There is a glass of orange juice.",
"There are some bananas.",
"There is a bowl of cereal.",
"Are these bananas?|No, they aren't.",
"Is this orange juice?|Yes, it is.",
"Is this a toast?|No, it isn't.",
"Is this a bowl of cereal?|Yes, it is.",
"My name is Max and this is my family.",
"We are eating dinner.",
"I'm eating fish.",
"He's eating soup.",
"She's eating salad.",
"They're eating chicken.",
"He's my father.",
"She's my mother.",
"What's this?|It's chicken.",
"What's this?|It's salad.",
"What's this?|It's fish.",
"What's this?|It's soup.",
"She's eating salad.",
"He's eating soup.",
"She's eating fish.",
"He's eating chicken.",
"Is Anna eating toast?|Yes, she is.",
"Is Meg eating cereal?|No, she isn't.",
"Is Jack eating eggs?|Yes, he is.",
"Is Sam eating fish?|No, he isn't.",
"He's eating eggs.",
"She's drinking milk.",
"He's drinking orange juice.",
"She's eating soup.",
"One table.",
"Two. chairs.",
"Three balls.",
"Four oranges.",
"Five ducks.",
"Six books.",
"Seven erasers.",
"Eight eggs.",
"Nine pencils.",
"Ten bananas.",
"How many bananas are there?|There are two bananas.",
"How many boys are there?|There are four boys.",
"How many girls are there?|There are three girls.",
"How many pencils are there?|There is only one pencil.",
"How many books are there?|There are five books.",
"How many schoolbags are there?|There are seven schoolbags.",
"How many apples are there?|There are nine apples.",
"Time for breakfast.|Let's go eat.",
"Time for breakfast.|What a treat.",
"Cereal, eggs, bananas and toast.",
"What kind of breakfast food do you eat the most?",
"Time for dinner.|Let's go eat.",
"Time for dinner.|What a treat.",
"Salad, soup, chicken and fish.",
"What kind of dinner is on you dish?",
"Is she eating bananas?|Yes, she is.",
"Is he eating soup?|No, he isn't.",
"Is she drinking milk?|No, she isn't.",
"Is he eating eggs?|Yes, he is.",
"What do you eat for breakfast?|I eat eggs and toast.",
"What do you eat for dinner?|I eat chicken.",
"What do you eat for breakfast?|I eat fruits.",
"What do you eat for dinner?|I eat soup.",
"What do you eat for dinner?|I eat salad."
];
