var unidad1 = [
  "a board.",
  "a door.",
  "a duck.",
  "a window.",
  "a book.",
  "a desk.",
  "an apple.",
  "a pencil.",
  "an eraser.",
  "a sharpener.",
  
  "it is a board.",
  "it is a sharpener.",
  "it is a pencil.",
  "it is a book.",
  "it is an eraser.",
  "it is a window.",
  
  "it is a door.",
  "it is a desk.",
  "it is an apple.",
  "it is a duck.",
  
  "what is this?|it is a sharpener.",
  "what is this?|it is a pencil.",
  "what is this?|it is a board.",
  "what is this?|it is a book.",
  
  "what is this?|it is an eraser.",
  "what is this?|it is a desk.",
  "what is this?|it is an apple.",
  "what is this?|it is a door."
];

var unidad2 = [
  "a teacher.",
  "a clock.",
  "a wall.",
  "a girl.",
  "a schoolbag.",
  "a boy.",
  "a ruler.",
  "a crayon.",
  "a trash can.",
  "a box.",
  
  "is this a schoolbag?|no, it is not.",
  "is this a clock?|yes, it is.",
  "is this a pencil?|no, it is not.",
  "is this an eraser?|yes, it is.",
  "is this a sharpener?|yes, it is.",
  "is this a girl?|no, it is not.",
  
  "is this a girl?|no, it is not.",
  "is this a box?|yes, it is.",
  "is this a wall?|no, it is not.",
  "is this a ruler?|yes, it is.",
  "is this a window?|yes, it is.",
  "is this a door?|no, it is not.",
  
  "it's a pencil.",
  "it's a wall.",
  "it's a ruler.",
  "it's a clock.",
  "it's an eraser.",
  "it's a pencil.",
  "it's an apple.",
  
  "what is this?|it is a trash can.",
  "what is this?|it is a window.",
  "what is this?|it is a wall.",
  "what is this?|it is a pencil.",
  "what is this?|it is an eraser.",
  "what is this?|it is a schoolbag.",
  
  "is this a girl?|yes, it is.",
  "is this a clock?not, it isn't.",
  "is this a crayon?|yes, it is.",
  "is this an eraser?|no, it isn't.",
  "is this a teacher?|yes, it is.",
  "is this a box?|no, it isn't.",

  "one girl.",
  "two clocks.",
  "three crayons.",
  "four pencils.",
  "five rulers.",
  "six sharpeners.",
  "seven schoolbags.",
  "eight erasers.",
  "nine boxes.",
  "ten windows.",

  "two trash cans.",
  "four rulers.",
  "three crayons.",
  "five pencils.",

  "this is a board.|this isn't a board.",
  "this is a crayon.|this isn't a crayon.",
  "this is a book.|this isn't a book.",
  "this is a duck.|this isn't a duck.",

  "it's a clock.",
  "it's a trash can.",
  "it's a box.",
  "it's a ruler.",

  "my schoolbag.|here it is.|come and have a look.|an eraser, an apple and a book.",
  "my schoolbag.|here it is.|come and have a look.|a ruler, a crayon and my book.",

  "can i borrow a pencil?|of course. here it is.",
  "can i borrow an eraser?|of course. here it is.",
  "can i borrow a sharpener?|of course. here it is."
];

var unidad3 = [
  "a cat.",
  "a dog.",
  "a fish.",
  "a bird.",
  "a mouse.",
  "a pigeon.",
  "is this a dog?|no, it isn't.",
  "is this a fish?|yes, it is.",
  "is this a cat?|no, it isn't.",
  "is this a pigeon?|yes, it is.",
  "is this a bird?|no, it isn't.",
  "red cat.",
  "blue bird.",
  "yellow duck.",
  "green fish.",
  "it's red.|it's a cat.",
  "it's blue.|it's a bird.",
  "it's yellow.|it's a duck.",
  "it's green.|it's a fish.",
  "the table is blue.",
  "the door is red.",
  "the trash can is yellow.",
  "the chair is blue.",
  "the mouse is green.",
  "the schoolbag is blue and red.",
  "what color is the table?|it's blue.",
  "what color is the mouse?|it's green.",
  "what color is the door?|it's red.",
  "what color is the trash can?|it's yellow.",
  "what color is the schoolbag?|it's blue and red.",
  "a fish.",
  "a cat.",
  "a dog.",
  "a bird.",
  "a mouse.",
  "a pigeon.",
  "red.",
  "blue.",
  "yellow.",
  "green.",
  "a green bird.",
  "a blue fish.",
  "a yellow cat.",
  "a blue pigeon.",
  "a red mouse.",
  "help me.|wait.|can't we be friends?|you're a cat.|i'm a dog.|We can't be friends.",
  "one mouse.",
  "two cats.",
  "three dogs.",
  "four fish.",
  "five books.",
  "six rulers.",
  "what's number one?|it's a red door.",
  "what's number two?|it's a green book.",
  "what's number three?|it's a blue cat.",
  "what's number four?|it's a yellow eraser.",
  "what's number five?|it's a red clock.",
  "what's number six?|it's a red fish.",
  "what's number seven?|it's a green dog.",
  "what's number eight?|it's a blue window.",
  "what's number nine?|it's a green pigeon.",
  "what's number ten?|it's a green board.",
  "it's a red fish.",
  "it's a yellow cat.",
  "it's a blue pigeon.",
  "it's a green mouse.",
  "is this a dog?|no, it isn't.|it's a cat.",
  "what's this?|it's a trash can.",
  "what color's your chair?|it's red.",
  "is this a bird?|yes, it is.",
];

var unidad4 = [
  "a monkey.",
  "a zookeeper.",
  "an elephant.",
  "a giraffe.",
  "a lion.",
  "orange.",
  "gray.",
  "brown.",
  "number one is a zookeeper.",
  "number two is a lion.",
  "number three is a monkey.",
  "number seven is a giraffe.",
  "number five is an elephant.",
  "this is a lion.|it's yellow.",
  "this is a monkey.|it's brown.",
  "this is an elephant.|it's gray.",
  "this is a bird.|it's orange and blue.",
  "number one is a yellow lion.",
  "number two is a brown giraffe.",
  "number three is a gray cat.",
  "number four is a blue fish.",
  "number five is a yellow giraffe.",
  "number six is a brown monkey.",
  "number seven is a gray elephant.",
  "number eight is a blue bird.",
  "pets.",
  "colors.",
  "zoo animals.",
  "blue.",
  "cat.",
  "dog.",
  "elephant.",
  "fish.",
  "giraffe.",
  "green.",
  "orange.",
  "monkey.",
  "the elephant is blue.",
  "the cat is yellow.",
  "the fish is red.",
  "the bird is green.",
  "the monkey is black.",
  "five blue fish.",
  "three green monkeys.",
  "two red elephants.",
  "four brown and yellow giraffes.",
  "it's a red trash can.",
  "it's a gray elephant.",
  "it's a black monkey.",
  "it's a brown lion.",
  "it's an orange box.",
  "it is a red sharpener.",
  "it isn't a green board.",
  "this isn't a blue window.",
  "it is a yellow pencil.",
  "this isn't a gray eraser.",
  "yes, it's a monkey.",
  "no, it's a chair.",
  "no, she's a teacher.",
  "yes, she's a girl.",
  "no, it's a lion.",
  "what's this?|it's a table.",
  "what's this?|it's a teacher.",
  "what's the number?|it's four.",
  "what color is it?|it's yellow.",
  "what's this?|it's a trash can.",
  "what's the number?|it's one.",
  "what's this?|it's a boy.",
  "what color is it?|it's red.",
  "what's this?|it's an elephant.",
  "what's the number?|it's five.",
  "what color is it?|it's orange.",
  "what's this?|it's a monkey.",
  "what color is it?|it's green.",
  "what color is it?|it's blue.",
  "what's this?|it's a lion.",
  "what's this?|it's a girl.",
  "what's the number?|it's three."
];

var unidad5 = [
"A cage.",
"A fishbowl.",
"A picture.",
"A sofa.",
"A ball.",
"An armchair.",
"A table.",
"The bird is in the cage.",
"The cat is on the sofa.",
"The dog is under the table.",
"The mouse is in the wall.",
"Where's the fish?|It's in the fishbowl.",
"Where is the cat?|It is in the trash can.",
"Where's the pigeon?|It's on the desk.",
"Where is the dog?|It is under the schoolbag.",
"Is the pigeon in the cage?|No, it isn't.",
"Is the cat in the trash can?|Yes, it is.",
"Is the dog on the schoolbag?|No, it isn't.",
"Is the mouse under the book?|Yes, it is.",
"The blue elephant is on the sofa.",
"The yellow lion is under the table.",
"The green elephant is in the box.",
"The brown lion is under the chair.",
"The yellow pigeon is in the schoolbag.",
"The orange tiger is on the armchair.",
"Where's the duck?|It's on the sofa.",
"Where is the dog?|It is under the elephant.",
"Where's the pigeon?|It's on the elephant.",
"Where is the orange cat?|It is under the box.",
"Where's the brown monkey?|It's on the sofa.",
"Where is the green bird?|It is in the cage.",
"Where's the black dog?|It's under the giraffe.",
"Where is the red monkey?|It is on the brown monkey.",
"The elephant is on the mouse.",
"The crayon is on the table.",
"The ball is under the chair.",
"The book is in the box.",
"The ruler is in the schoolbag.",
"Is the monkey in the classroom?|Yes, it is.",
"Is the monkey on the sofa?|No, it isn't.",
"What color is the monkey?|It's brown.",
"Where's the sharpener?|It's on the desk.",
"Do you have a pet?|Yes, I do. I have a dog."
];

var unidad6 = [
"House.",
"Family.",
"Grandmother.",
"Mother.",
"Grandfather.",
"Father.",
"Baby.",
"Sister.",
"Brother.",
"Who's she?|She's the mother.",
"Who's he?|He's the grandfather.",
"She is the mother.",
"He is the father.",
"He is the grandfather.",
"He is the brother.",
"She is the baby.",
"She is the sister.",
"She is the grandmother.",
"This is my family.",
"There are four people in my family.",
"My mother, father, big brother and me.",
"My mom and dad take care of us so well.",
"They help and hug us.|They're really swell.",
"My big brother is so much fun.",
"We laugh and play, jump and run.",
"We're such a happy family.",
"My mother, father, big brother and me.",
"Where's my book?|It's under the soffa.",
"Where's my eraser?|It's on the armchair.",
"Where's my pencil?|It's in the box.",
"Where's my sharpener?|It's under the table.",
"Five babies.",
"Seven monkeys.",
"Eight pictures.",
"Nine balls.",
"Six chairs.",
"Where's Harry?|Is he on the sofa?|Is he in the trash can?",
"Is he in the tub?|Where's Harry?|Oh, here you are, Harry.",
"Who is he?|He is the grandfather.",
"Who's she?|She's the grandmother.",
"Who's he?|He's the father.",
"Who is she?|She is the mother.",
"Who is he?|He is the brother.",
"Who's she?|She's the sister.",
"Who's he?|He's the son.",
"Who is she?|She is the daughter.",
"How many brothers and sisters do you have?|One sister and one brother.",
"Mother and father.",
"Monkey and baby.",
"Brother and boy.",
"Sofa and chair.",
"Table and desk.",
"Red, green, yellow and blue.",
"Ball, book, eraser and pencil.",
"Pigeon, cat, dog and bird.",
"Box and sharpener."
];

var unidad7 = [
  "curtains.",
"lamp.",
"mirror.",
"plant.",
"rug.",
"shower.",
"sink.",
"toilet.",
"toothbrush.",
"towel.",
"living room.",
"bathroom.",
"the toilet is in the bathroom.",
"the rug is in the living room.",
"the duck is in the sink.",
"the cat is on the girl.",
"there is a plant in the living room.",
"there isn't a clock in the picture.",
"there is a red table in the living room",
"there isn't a brown towel in the bathroom.",
"there is a plant in the living room.",
"there isn't a yellow sink in the bathroom.",
"there is a chair in the living room.",
"there isn't a ball in the bathroom.",
"there are three toilets.|color them blue.",
"there are six toothbrushes.|color them red.",
"there are two showers.|color them green.",
"there are two lamps.|color them brown.",
"there are four towels.|color them orange.",
"there are two green showers.",
"there are three blue toilets.",
"there are two brown lamps.",
"there are six red toothbrushes.",
"three pictures.",
"there is one rug in the living room.",
"there ara five plants in the living room.",
"there is one sofa in the living room.",
"there are two armchairs in the living room.",
"there are tow tables in the kitchen.",
"there are eight chairs in the kitchen.",
"there are two trash cans in the kitchen.",
"there are seven curtains in the living room.",
"there is one window in my bathroom.",
"there are three towels in my bathroom.",
"my plant is green.",
"the towel is red.",
"the picture is big.",
"the curtains are white.",
"the mirror is in the bathroom.",
"the door is brown.",
"there are four windows in the house.",
"there are two rugs in the living room.",
"there are five towels in the bathroom.",
"there's a red sofa.",
"there's a clock on the wall.",
"the dog is on the rug.",
"the duck is on the armchair.",
"this is a bathroom.",
"there's a blue toilet.",
"there's a brown sink.",
"there are two orange towels on the wall.",
"there's a plant on the green table.",
"what room is this?|it's a bathroom.",
"what color is the sink?|it's a brown sink.",
"where are the towels?|there are on the wall.",
"how many rooms are there in your house?|there are six rooms.",
"what is this?|it is a mirror.",
"what's this?|it's a shower.",
"what is this?|it is a plant.",
"what's this?|it's a toilet."
];

var unidad8 = [
  "They are talking.",
"He is running.",
"They're playing.",
"She's jumping rope.",
"They're eating.",
"They're doing homework.",
"They're eating.",
"He's jumping rope.",
"They're talking.",
"They're playing.",
"She's doing homework.",
"They're running.",
"What's the grandfather doing?|He's walking.",
"What's the baby doing?|The baby's sleeping.",
"What's the mother doing?|She's reading.",
"What's the sister doing?|She's riding a bike.",
"The mother's reading.",
"The baby's sleeping.",
"The sister's riding a bike.",
"The grandfather's walking.",
"Is the girl walking to school?|Yes, she is.",
"Is the boy playing with his dog?|No, he isn't.",
"Is the girl sleeping on the sofa?|No, she isn't.",
"Is the boy reading in his bed?|Yes, he is.",
"The monkey is riding a bike.",
"The giraffe is reading.",
"The cat and the mouse are playing.",
"The pigeons are sleeping.",
"The dog is eating.",
"The elephant is talking.",
"He is running.",
"She is walking.",
"I'm jumping rope.",
"They're playing soccer.",
"We're reading.",
"I'm playing with my dog.",
"He's jumping?",
"She's doing homework.",
"We're eating.",
"They're riding a bike.",
"He's walking the dog.",
"I like reading.|Yes, I do.",
"Reading is so much fun.|Yes, it is.",
"I like running.|Yes, I do.",
"Running is so much fun.|Yes, it is.",
"I like jumping rope.",
"The dog is running in the park.",
"They're reading in the classroom.",
"She's reading a book in the living room.",
"The baby is sleeping on the sofa.",
"He's riding a bike in the park.",
"The giraffe is eating an apple.",
"The grandfather and the grandmother are walking.",
"Eleven fishes.",
"Twelve balloons.",
"Thirteen crayons.",
"Fourteen pencils.",
"Fifteen sharpeners.",
"Sixteen clocks.",
"Seventeen erasers.",
"Eighteen apples.",
"Nineteen mirrors.",
"Twenty colors.",
"The boy is walking the dog.",
"The boy is doing homework.",
"The girl is reading.",
"The girl is jumping.",
"The mother is jumping rope.",
"The father is walking the dog.",
"They're playing.",
"The boy is sleeping.",
"The dog is eating.",
"What do you like to do?|I like reading and walking.",
"What do you like to do?|I like riding a bike.",
"What do you like to do?|I like running.",
"What do you like to do?|I like walking the dog.",
"What do you like to do?|I like sleeping.",
"What do you like to do?|I like eating apples."
];
  
var unidad9 = [
"These are toy cars.",
"These are board games.",
"These are balloons.",
"These are toys.",
"These are toy animals.",
"This is a closet.",
"This is a bookcase.",
"This is a laptop.",
"This is a tv.",
"This is a bed.",
"These are puzzles.",
"What are they?|They're three books.",
"What are they?|They're two board games.",
"What are they?|They're six toy animals.",
"What are they?|They're eight crayons.",
"There is a trash can.",
"There are four tables.",
"There is a plant.",
"There are six toy animals.",
"How many tables are there?|There are four tables.",
"What color are the tables?|They're red, blue and yellow.",
"Where are the crayons?|They're on the green table.",
"Where's the trash can?|It's on the floor.|It's under the blue table.",
"There is a brown bed in my bedroom.",
"There are two beds in my bedroom.",
"There is a laptop on the table.",
"There are two laptops on the table.",
"There is a blue lamp in my bedroom.",
"There are two blue lamps in my bedroom.",
"There are two windows in my bedroom.",
"There is a window in my bedroom.",
"There is a table in the living room.",
"There are two tables in the living room.",
"There is a chair in the living room.",
"There are two chairs in the living room.",
"There is an armchair in the living room.",
"There are two armchairs in the living room.",
"There is a closet in my bedroom.",
"There are two closets in my bedroom.",
"There is a bookcase in my bedroom.",
"There are two bookcases in my bedroom.",
"There is a rug in the living room.",
"There are two rugs in the living room.",
"There is a picture in the living room.",
"There are two pictures in the living room.",
"There is a plant in the living room.",
"There are two plants in the living room.",
"I'm scared. There is a monster at the window.|No. They're the curtains.",
"What's that in the closet?|It's only a puppet.",
"Look at the door.|Who's there?|it's my mommy.",
"There's a lion over there.|It's not a lion. It's clothing.",
"There's a mouse.|No. It's my hamster.",
"No more playing.|Time to go to sleep.",
"What do you do in your bedroom?|I play with my toys."
];

var maxUnidades = 9;
