var unidad1 = [
"I'm Tom.|I'm eight.|How about you?",
"I'm Olga.|I'm nine.|Nice to meet you.",
"I'm Mark.|How old are you?|I'm nine.",
"How many boats can you see?|I see twelve boats.",
"Come on Jhon, count with me.",
"Orange, yellow, green and blue.",
"I'm ready for school.|Yes, school is cool.",
"I have my big Schoolbag.|And my sharpener too.",
"I have my books and my pencils.|How about you?",
"I have my favorite ruler.|An my pencil case.",
"I have my pen and my eraser.|And a smile on my face.",
"The pencil case is yellow.",
"The pencil is red.",
"The book is blue.",
"The ruler is green.",
"The pen is black.",
"The sharpener is red.",
"The schoolbag is purple.",
"The eraser is pink and red.",
"Hello Karim.|Hi Lucy.",
"Do you have a pencil?|Yes, I do.|Here you are.",
"Do you have an eraser?|Yes, I do.",
"Thanks. Do you have a ruler?|No. I don't. Sorry.",
"Do you like my picture?|Yes. It's very interesting.",
"Do you have a blue pen?|Yes, I do.",
"Do you have a blue pencil case?|No. I don't.",
"Do you have a blue schoolbag?No. I have a pink and black schoolbag.",
"The children are at the zoo.|They're drawing the monkeys.",
"Tom likes this monkey.",
"Hurry up, Tom.",
"Let's go and see the crocodiles.",
"Tom leaves his hat and coat on the chair.",
"Tom leaves his bag under the trash can.",
"What is the monkey doing?",
"The monkey is putting on Tom's jacket and hat.",
"The monkey has Tom's schoolbag.",
"Tom isn't drawing and the teacher isn't happy.",
"Look at the monkey.",
"I don't have my schoolbag.",
"Now the children are in the snake house.",
"Look at the monkey, Tom.|It's behind you.",
"It's time for lunch.",
"I have sandwiches.",
"I have fruit and yogurt.",
"Tom. Come down now.",
"The monkey has Tom's lunch box.",
"The teacher is very angry now.",
"Look behind you, monkey.",
"Look, monkey.|I have a banana.",
"The monkey is in the cage again.|It's time to go back to school.",
"Good bye, monkey.",
"Tom, where are your sunglasses?",
"Where's the book?|Look and find.",
"In, on, under or behind.",
"There it is.|I can see.",
"It's under the table.",
"Where's the ruler?|It's in the schoolbag.",
"Where's the ball?|It's on the chair.",
"Can I have four boxes of colored pencils, please?|Yes, follow me.",
"Robby is helping Beep in the stationery store.",
"And can I have two electric sharpeners?|Yes, they're on the table.",
"And three pencil cases and six erasers.|Here you are.",
"And four, five, six erasers.",
"And fourteen blue pens, eleven black pens and five rulers.",
"And five rulers.|And a schoolbag, please.",
"Be careful, Robby.",
"Robby, the very big schoolbags are behind you.",
"Pink and purple pencils.",
"Pens and pencil cases.",
"Peter and Patricia.",
"Drawing funny faces."
];

var unidad2 = [
"Look at the clock.",
"It is a busy morning.|I can't stop.",
"Get up now.",
"I brush my teeth.",
"Hurry up.",
"I'm still asleep.",
"Take a shower.",
"Get dressed, quick.",
"I have my breakfast.",
"It's great.",
"I go to school.",
"I'm late.",
"I get up.",
"I brush my teeth.",
"I take a shower.",
"I get dressed.",
"I have breakfast.",
"I go to school.",
"Hello Olga.|Get up, please.",
"What time is it?|It's eight o'clock.",
"Olga, go to school, please.",
"What time is it?|It's eight thirty.",
"Ok, Mom.|Bye.",
"Bye, Olga.",
"What time is it?|It's three o'clock.",
"What time is it?|it's nine thirty.",
"What time is it?|It's two thirty.",
"What time is it?|It's ten o'clock.",
"What time is it?|It's seven o'clock.",
"What time is it?|It's five thirty.",
"I have my breakfast at eleven o'clock.",
"I take a shower at nine thirty.",
"I brush my teeth at eleven thirty.",
"I get up at nine o'clock.",
"I go to school at noon.",
"I get dressed at ten thirty.",
"Lucy has a new watch.|It can talk.",
"It's nine o'clock.|Brush your teeth.",
"It's time for bed.",
"It's morning.",
"It's seven o'clock.|Time to get up.",
"Lucy's new watch is very smart.",
"It's time to take a shower.",
"Where's Tom?|Tom is still asleep.",
"Tom, get dressed.|I'm tired.",
"It's eight o'clock.|It's time for breakfast.",
"Hurry up, Tom|You're late for school.",
"It's eighth thirty.",
"Quick, Tom.|Eat your breakfast.",
"Where are Mom and Dad?",
"Tom and Lucy look for Mom and Dad in he living room.",
"Where are they?|We're late.",
"Get up, Mom.|We're late for school.|But it's Saturday.",
"Tom likes Saturday.|There's no school.",
"Monday.",
"Tuesday.",
"Wednesday.",
"Thursday.",
"Friday.",
"Saturday.",
"Sunday.",
"I get up and go to school.",
"I see my friends.",
"School is cool.",
"Lots to do and lots to see.",
"My favorite days are Saturday and Sunday.",
"It's time to play.",
"I read a book.",
"They ride bikes.",
"He swims.",
"She sings.",
"They eats pizza.",
"She plays soccer.",
"He plays computer games.",
"My name's Marco.",
"My favorite day is Saturday.",
"I get up at ten o'clock.",
"I ride my bike with my dad in the park.",
"I have a black bike.",
"My name is Emma.",
"My favorite day is Wednesday.",
"I get up at seven thirty.",
"I play basketball with my friends at school.",
"I like basketball.",
"What's your favorite day?|It's Friday.|I play computer games on Friday.",
"It's twelve o'clock.|Robby's asleep.",
"I can't sleep.",
"It's two o'clock.|Beep's counting sheep.",
"Counting sheeps doesn't work.|I still can't sleep.",
"It's three o'clock.|Beep has another idea.|He's reading.",
"This is a fantastic magazine.",
"It's five o'clock and Beep still can't sleep.",
"I know.|I'll eat some ice cream.",
"It's six thirty and Beep's asleep.",
"Get up, Beep.|It's seven o'clock.",
"When Beep can't sleep, he counts sheep.",
"When Beep can't sleep, he reads a magazine.",
"When Beep can't sleep, he eats ice cream."
];

var unidad3 = 
    ["Superhero.",
"Princess.",
"Dwarf.",
"Prince.",
"Giant.",
"Pirate.",
"Dragon.",
"Witch.",
"Come to Story World.",
"Everybody's there.",
"A prince and a princess.",
"With long black hair.",
"A dragon and a witch.",
"With a little black cat.",
"And there's a big pirate.",
"With a black and white hat.",
"There's a dwarf and a giant.",
"With his head in the sky.",
"And look the superhero.",
"She can fly.",
"Come to Story World.",
"Don't be late.",
"We love stories.",
"Stories are great.",
"Look at the giant.|He's tall.",
"Look at the dwarf.|He's short.",
"Can you see the pirate?|He's fat.",
"Look at the witch.|She's thin.",
"I like the superhero.|She's strong.",
"I don't like the dragon.|He's scary.",
"Am I scary, Olga?|No, Karim.|You aren't scary.",
"The children are in the school play.",
"It's sleeping beauty.",
"Karim is in the play.",
"This is his sister, Sandra.",
"The princess lives in a big castle.",
"Ah, Olga is the princess.",
"Look at her dress.",
"Here's Lucy.|She's the witch.",
"Go to sleep, princess.",
"Oh no.|She's scary.",
"The princess is sleeping.",
"Look, now there are a lot of trees.",
"It's Tom.|He's the prince.",
"And Karim is his horse.",
"He's funny.",
"The prince is cutting down the trees with his sword.",
"Don't worry, princess.|I'm coming.",
"He's very strong.",
"Oh, no.|Olga is really asleep.",
"I'm the prince.|Wake up, princess.",
"Pleace, wake up, princess.",
"Look out, Karim.",
"Where am I?",
"It's a very funny story.",
"Everyone likes the play.",
"This is the witch.",
"She has a cat.",
"Her nose is big.",
"Her hat is black.",
"This is a princess.",
"She has a crown.",
"Her shoes are red.",
"Her hair is brown.",
"This is the prince.",
"And his horse too.",
"His arms are strong.",
"HIs eyes are blue.",
"Her hair is green.",
"His kite is blue.",
"Her shoes are orange.",
"His jacket is purple.",
"Her cat is white.",
"HIs book is green.",
"Her hair is red.",
"HIs jacket is orange.",
"His ears are green.",
"His eyes are yellow.",
"He is scary.",
"What's his name?",
"His hair is short and yellow.",
"His cape is red.",
"What's his name?",
"His leg are thin.",
"He is small and strong.",
"What's his name?",
"Her hair is red.",
"Her legs are purple.",
"She is thin.",
"What's her name?",
"This is supergirl.",
"Her hair is pink.",
"She's strong.",
"This is a supermonster.",
"He has blue hands and legs.",
"He's scary.",
"Hello boys, come in.",
"Beep and Robby are at a costume party.",
"They're wearing cowboy costumes.",
"What a bad pirate.",
"Now he's taking her bag.",
"I have an idea.",
"Fantastic costumes.",
"It's not a costume.",
"We are the police.",
"Robby sees the pirate taking a necklace.",
"Beep stops the pirate with his lasso.",
"I have you.",
"Beep and Robby are heroes.",
"Thank you.",
"Giants like flying kites.",
"Pirates like riding bikes.",
"I like climbing.",
"What do you like?",
"Monday.",
"Thursday.",
"Saturday.",
"Wednesday.",
"Friday.",
"Sunday.",
"Tuesday.",
"What time is it?",
"Touch a schoolbag.",
"Where's the spider?",
"Is he tall.",
"Do you have a ruler?|Yes, I do.",
"Do you have a black pen?|No, I don't.",
"Do you have a white eraser?|Yes, I do.",
"Do you have a red pencil?|No, I don't.",
"Do you have a blue schoolbag?|Yes, I do.",
"Do you have a pencil case?|No, I don't."
];

var unidad4 = ["Sports are great.",
"Sports are fun.",
"Lots of sports for everyone.",
"I like tennis.|Yes, I do.",
"I like rollerblading too.",
"I like riding in the sun.",
"I like basketball.|It's fun.",
"I like swimming in the pool.",
"I like gymnastics.|It's so cool.",
"I like skiing in the snow.",
"I like soccer.|See me go.",
"Do you like soccer?|Yes, I do.",
"Do you like gymnastics?|No, I don't.",
"Do you like tennis?|Yes, I do.",
"Do you like swimming?|No, I don't.",
"Do you like rollerblading?|Yes, I do.",
"Do you like basketball?|No, I don't.",
"Do you like riding a bike?|Yes, I do.",
"Do you like skiing?|No, I don't.",
"Do you like photos?|Yes, I do.",
"Is this your family?|Yes.|Look at my mom.|She likes gymnastics.",
"Your mom likes gymnastics.|But your dad doesn't like skiing.",
"My dad doesn't like skiing.|He can't ski.",
"Look, my sister likes rollerblading.",
"Here's your grandpa.|He likes tenis.",
"And this is my grandma.|She doesn't like soccer.",
"She isn't happy.|Poor grandma.",
"He doesn't like skiing.",
"She likes basketball.",
"He likes riding bike.",
"She doesn't like tennis.",
"She likes gymnastics.",
"He likes soccer.",
"She doesn't like rollerblading.",
"He likes swimming.",
"She is my friend, Andrea.",
"She likes tennis and soccer.",
"She doesn't like rollerblading.",
"The soccer starts soon.|Oh no, we're late.",
"It's field day.",
"Karim is on the soccer team.",
"Olga is in the gymnastics competition.",
"Lucy is in the bike race.",
"And Tom is in the rollerblading race.",
"What's this?|It's a soccer shirt.",
"You have Karim's bag.|Don't worry.|I have an idea.",
"This isn't my bag.|It's OK.|I can help.",
"Tom has an idea.",
"Look at Lucy.|She can ride fast.",
"It's nearly two o'clock.|The soccer game is starting.",
"Tom likes rollerblading.",
"Hey, look.|There's Tom.",
"He can rollerblade very fast.",
"Karim likes soccer.|He can run fast and score lots of goals.",
"Good work, Karim.",
"Olga is very good at gymnastics.|She can walk on her hands.",
"You're fantastic, Olga.",
"Later that day.",
"Olga, that's my cup.|No, it isn't.",
"His name is Patrick.|He can do gymnastics.",
"Her name is Jade.|She can rollerblade.",
"His name is Mike.|He can ride a bike.",
"Her name is Kim.|She can swim.",
"His name is Paul.|He can juggle balls.",
"He name is Doris.|She can climb trees.",
"Tom can climb a tree.",
"Do you like sack races?|Yes, I do.",
"Do you like wheelbarrow races?|No, I don't.",
"Does she like running races?|Yes, she does.",
"Does he like three legged races?|No, he doesn't.",
"I'm from the United States.",
"Look at the photos of the school.",
"Field day at my school.",
"In this photo, there are boys and girls.|They are running.",
"In this photo, there are four girls.|Look, they have three legs.",
"In this photo, there are two boys and a girl.|They're jumping.",
"In this photo, there are two boys.|One boy is walking in his hands.",
"What's your favorite race?",
"Can you walk on your hands?",
"Can you run fast?",
"Do you have a medal?",
"Beep and Robby are in the mountains.|Robby likes skiing.",
"Come on Beep, let's go.",
"Beep doesn't like skiing but Robby can ski very fast.",
"This is fantastic.",
"Look out.|There's a rock.",
"Look at Robby.|He can jump.",
"I like skiing.",
"Look at Robby.|He can ski on one leg.",
"Be careful Robby.",
"Robby can ski very fast.",
"Robby.|Look out.",
"Don't worry, Beep.",
"Look at Robby now.|He can fly.",
"Robby.|You're fantastic.",
"Jane can juggle lots of balls.",
"Jim can do gymnastics.",
"Jhon can jump and Jerry can jog.",
"I think they're all fantastic."];

var unidad5 = 
["Come to the nature park with me.",
"There's lots to do and lots to see.",
"Animals, animals everywhere.",
"A big gray wolf, a big brown bear.",
"There's an eagle in the sky.",
"Look. A pretty butterfly.",
"A squirrel climbing in a tree.",
"A spider next to me.",
"See the fish in the lake.",
"Look behind you.|There is a snake.",
"The bear is big and brown.",
"The snake is green.",
"The eagle flies in the sky.",
"The spider is small and red.",
"The wolf is in the forest.",
"The blue fish is in the lake.",
"The yellow butterfly is in the flower.",
"The squirrel is brown.",
"Does the wolf have legs?|Yes, it does.",
"Does the spider have wings?|No, it doesn't.",
"Does the bear have brown hair?|Yes, it does.",
"It has wings.|It doesn't have tail.|It's a butterfly.",
"It has four legs.|It doesn't have wings.|It's a wolf.",
"It has eight legs.|It doesn't have claws.|It's a spider.",
"It has tail.|It doesn't have legs.|It's a fish.",
"The children are at the nature park.",
"Welcome to the nature park.",
"Come on Olga.|Let's go for a walk.|Be careful.",
"Olga can see an animal.",
"What's that?|It don't know.|It has a big tail.",
"Look at the squirrel.|It can climb very fast.",
"Help.|It's a wolf.|Don't be silly, Olga.|It's a squirrel.",
"Olga can see something scary with her binocular.",
"It's a horrible monster.|Don't be silly, Olga.|It's just a spider.",
"The spider can't hurt you.",
"It has big eyes and hairy legs.",
"It's a bear.|It has big teeth and claws.",
"It's time to go home.",
"Thanks for the bear costume.",
"A fish can swim.|Yes, it can.",
"A fish can swim all day.",
"Can the fish climb a tree?|No, it can't.",
"A squirrel can climb.|Yes, it can.",
"A squirrel can climb all day.",
"Can the squirrel fly in the sky?|No, it can't.",
"An eagle can fly.|Yes, it can.",
"An eagle can fly all day.",
"Can the eagle swim in the lake?|No, it can't.",
"Can a bear swim?|Yes, it can.",
"Can it climb trees?|Yes, it can.",
"Can it fly?|No, it can't.",
"Can a wolf jump?|Yes, it can.",
"Can it climb trees?|Yes, it can.",
"Can it swim?|No, it can't.",
"It has claws.",
"It doesn't have wings.",
"It can climb trees.",
"It's strong.",
"It doesn't have legs.",
"It can swim.",
"It can't climb trees.",
"It's gray.",
"It has wings.",
"It can swim.",
"It can't fly.",
"It's black and white.",
"It has a tail.",
"It doesn't have wings.",
"It can climb trees.",
"It can't fly.",
"They're having a picnic.",
"Squirrels are my favorite animals.",
"What's the squirrel doing?",
"Here's my banana.",
"Where's my sandwich?",
"Look at the squirrel.|It has a sandwich.",
"Now it has the Olgas's banana.",
"What a scary wolf.",
"Now the squirrel is eating the banana.",
"Where's my banana?",
"It's the squirrel.",
"Squirrels are not my favorite animals.",
"Birds and butterfly everywhere.",
"Look behind you.",
"A big, bad bear."]

var unidad6 = [
"After school there's a lot to do.",
"Lots of fun for me and you.",
"I like making models.|And I like playing cards.",
"I like doing puzzles.|And playing the guitar.",
"I like singing songs.|And I like dancing too.",
"I like gardening.",
"I like reading.|How about you?",
"I like making models.",
"He likes playing cards.",
"She likes singing.",
"We like dancing.",
"You like gardening.",
"I like reading.",
"They like playing guitar.",
"We like doing puzzles.",
"He's reading a comic.",
"What's Grandpa doing?|He's making models.",
"What's Mom doing?|She's playing guitar.",
"What's Grandma doing?|She's doing a puzzle.",
"And Dad?|What's Dad doing?|He's reading.",
"What are you doing?|I'm drawing you.",
"What's Karim doing?|He's doing a puzzle.",
"What's Lucy doing?|She's playing guitar.",
"What's Pat doing?|He's gardening.",
"What's Olga doing?|She's playing cards.",
"What's Emma doing?|She's reading a book.",
"What's Tom doing?|He's singing a song.",
"The children are playing hide and seek.",
"Let's hide in the bedroom.",
"Here's Dad.|He's making a model.",
"Hi, Dad.|Where's Tom?|I don't know.",
"Here's Mom.|She's gardening.",
"Hi, Mom.|Where's Olga?|She's in the bedroom, with Lucy.",
"Here are Olga and Lucy.",
"I can see you.|Come out.",
"Here's Sandra.|She's playing the guitar.",
"Hi Sandra.|Where's Tom?|I don't know.",
"Here's Grandpa.|He's playing cards.",
"Hi, Grandpa.|Where's Tom?|He's in the kitchen.",
"They can't find Tom.",
"I'm bored.|Let's have some cookies.",
"He's in the cupboard.|He's eating all the cookies.",
"Where's Dad?|He's in the bathroom.",
"Where's Mom?|She's in the car.",
"Where's Sandra?|She's in her bedroom.",
"She's playing the guitar.",
"Where's Grandma?|She's in the kitchen.",
"Where is Grandpa?|He is in the hall.",
"Where is Karim?|He is in the garden.",
"He is playing basketball.",
"I like doing puzzles.",
"You like dancing.",
"He likes gardening.",
"She likes making models.",
"We like playing cards.",
"They like playing the guitar.",
" They are playing cards.",
"It's your turn.",
"What are you doing?|I'm making a model.",
"Let's take a photo.",
"Where's my camera?",
"What's he doing?|He's playing cards.",
"He is good at gardening.",
"She is good at guitar.",
"I'm good at playing golf.",
"He's a superstar."];

var unidad7 = [
"Traveling everywhere.",
"A bus and a train to get you there.",
"Traveling on the sea.",
"A big ship and a boat for me.",
"Traveling in the sky.",
"A plane and a helicopter flying high.",
"Traveling on the street.",
"A bike and a car and my two feet.",
"What's this?|It's a car.",
"What's this?|It's a boat.",
"What's this?|It's a helicopter.",
"What's this?|It's a train.",
"What's this?|It's a bus.",
"What's this?|It's a bike.",
"What's this?|It's a ship.",
"What's this?|It's a plane.",
"The bus is red.",
"The helicopter is yellow.",
"The bike is pink.",
"The plane is white.",
"The train is green.",
"The boat is red and white.",
"The car is blue.",
"The ship is gray.",
"Is your card old?|No, it isn't.|It's new.",
"Is it slow?|No, it isn't.|It's fast.",
"Is it big?|No, it isn't.|It's small.",
"Is your car green?|Yes, it is.|Do you like it?",
"Is the brown plane old?|Yes, it is.",
"Is the red bus slow?|No, it isn't.",
"Is the blue boat big?|No, it isn't.",
"Is the white plane fast?|Yes, it is.",
"Is the pink bike big?|No, it isn't.",
"Is the green car new?|Yes, it is.",
"The children are visiting a lighthouse today.",
"Get off the bus now.",
"The boat is arriving at the lighthouse.",
"Look at the helicopter.",
"There's the lighthouse keeper.",
"When it's night, the ships can see the light.",
"Karim and Olga are going up the stairs.",
"Let's go and see the light.",
"Look at the plane.",
"The boat is going.|We're late.",
"Olga and Karim are late for the boat.",
"Wait for us.|Don't worry.|I can take you by helicopter.",
"Karim and Olga are flying in the helicopter.",
"This is fantastic.",
"Going up, seventy meters.",
"The boat is slow but the helicopter is very fast.",
"What are you doing here?",
"Ten, twenty, racing cars.",
"Thirty, forty, going far.",
"Fifty, sixty, fast and slow.",
"Seventy, eighty, see them go.",
"Ninety and a hundred, little racing cars.",
"Can children fly in hot-air balloons?",
"Can hot-air balloons fly at night?",
"Can hot-air balloons fly in the rain?",
"Can hot-air balloons go fast?",
"They have a new car.",
"That bus is very slow.",
"I like the new car.",
"It is very fast.",
"The car is dirty now.",
"Let's go to the car wash.",
"They are at the car wash.",
"This is very slow.",
"Close your car windows.",
"The window are open.",
"Now the car is clean.|They are clean too.",
"He travels by tractor.",
"She travels by plane.",
"My friends like to travel by train."];

var maxUnidades = 7;
