var unidad1 = [
  "a board",
  "a door",
  "a duck",
  "a window",
  "a book",
  "a desk",
  "an apple",
  "a pencil",
  "an eraser",
  "a sharpener",
  
  "it is a board",
  "it is a sharpener",
  "it is a pencil",
  "it is a book",
  "it is an eraser",
  "it is a window",
  
  "it is a door",
  "it is a desk",
  "it is an apple",
  "it is a duck",
  
  "what is this?|it is a sharpener",
  "what is this?|it is a pencil",
  "what is this?|it is a board",
  "what is this?|it is a book",
  
  "what is this?|it is an eraser",
  "what is this?|it is a desk",
  "what is this?|it is an apple",
  "what is this?|it is a door"
];

var unidad2 = [
  "a teacher",
  "a clock",
  "a wall",
  "a girl",
  "a schoolbag",
  "a boy",
  "a ruler",
  "a crayon",
  "a trash can",
  "a box",
  
  "is this a schoolbag?|no, it is not.",
  "is this a clock?|yes, it is.",
  "is this a pencil?|no, it is not.",
  "is this an eraser?|yes, it is.",
  "is this a sharpener?|yes, it is.",
  "is this a girl?|no, it is not.",
  
  "is this a girl?|no, it is not.",
  "is this a box?|yes, it is.",
  "is this a wall?|no, it is not.",
  "is this a ruler?|yes, it is.",
  "is this a window?|yes, it is.",
  "is this a door?|no, it is not.",
  
  "it's a pencil",
  "it's a wall",
  "it's a ruler",
  "it's a clock",
  "it's an eraser",
  "it's a pencil",
  "it's an apple",
  
  "what is this?|it is a trash can.",
  "what is this?|it is a window.",
  "what is this?|it is a wall.",
  "what is this?|it is a pencil.",
  "what is this?|it is an eraser.",
  "what is this?|it is a schoolbag.",
  
  "is this a girl?|yes, it is.",
  "is this a clock?not, it isn't.",
  "is this a crayon?|yes, it is.",
  "is this an eraser?|no, it isn't.",
  "is this a teacher?|yes, it is.",
  "is this a box?|no, it isn't.",

  "one girl",
  "two clocks",
  "three crayons",
  "four pencils",
  "five rulers",
  "six sharpeners",
  "seven schoolbags",
  "eight erasers",
  "nine boxes",
  "ten windows",

  "two trash cans",
  "four rulers",
  "three crayons",
  "five pencils",

  "this is a board.|this isn't a board.",
  "this is a crayon.|this isn't a crayon.",
  "this is a book.|this isn't a book.",
  "this is a duck.|this isn't a duck.",

  "it's a clock",
  "it's a trash can",
  "it's a box",
  "it's a ruler",

  "my schoolbag, my schoolbag.|here it is. come and have a look.|an eraser, an apple and a book.",
  "my schoolbag, my schoolbag.|here it is. come and have a look.|a ruler, a crayon and my book.",

  "can i borrow a pencil?|of course. here it is.",
  "can i borrow an eraser?|of course. here it is.",
  "can i borrow a sharpener?|of course. here it is."
];

var unidad3 = [
  "a cat",
  "a dog",
  "a fish",
  "a bird",
  "a mouse",
  "a pigeon",
  "is this a dog?|no, it isn't.",
  "is this a fish?|yes, it is.",
  "is this a cat?|no, it isn't.",
  "is this a pigeon?|yes, it is.",
  "is this a bird?|no, it isn't.",
  "red cat",
  "blue bird",
  "yellow duck",
  "green fish",
  "it's red.|it's a cat.",
  "it's blue.|it's a bird",
  "it's yellow.|it's a duck.",
  "it's green.|it's a fish.",
  "the table is blue.",
  "the door is red.",
  "the trash can is yellow.",
  "the chair is blue.",
  "the mouse is green.",
  "the schoolbag is blue and red.",
  "what color is the table?|it's blue.",
  "what color is the mouse?|it's green.",
  "what color is the door?|it's red.",
  "what color is the trash can?|it's yellow.",
  "what color is the schoolbag?|it's blue and red.",
  "a fish",
  "a cat",
  "a dog",
  "a bird",
  "a mouse",
  "a pigeon",
  "red",
  "blue",
  "yellow",
  "green",
  "a green bird",
  "a blue fish",
  "a yellow cat",
  "a blue pigeon",
  "a red mouse",
  "help me!|wait! can't we be friends?|you're a cat. I'm a dog. We can't be friends!",
  "one mouse",
  "two cats",
  "three dogs",
  "four fish",
  "five books",
  "six rulers",
  "what's number one?|it's a red door.",
  "what's numer two?|it's a green book.",
  "what's number three?|it's a blue cat.",
  "what's number four?|it's a yellow eraser.",
  "what's number five?|it's a red clock.",
  "what's number six?|it's a red fish.",
  "what's number seven?|it's a green dog.",
  "what's number eight?|it's a blue window.",
  "what's number nine?|it's a green u.",
  "what's number ten?|it's a green board.",
  "it's a red fish.",
  "it's a yellow cat.",
  "it's a blue pigeon.",
  "it's a green mouse.",
  "is this a dog?| no, it isn't.|it's a cat.",
  "what's this?|it's a trash can.",
  "what color's your chair?|it's red.",
  "is this a bird?|yes, it is.",
];

var unidad4 = [
  "a monkey",
  "a zookeeper",
  "an elephant",
  "a giraffe",
  "a lion",
  "orange",
  "gray",
  "brown",
  "number one is a zookeeper",
  "number two is a lion",
  "number three is a monkey",
  "number seven is a giraffe",
  "number five is an elephant",
  "this is a lion.|it's yellow.",
  "this is a monkey.|it's brown.",
  "this is an elephant.|it's gray.",
  "this is a bird.|it's orante and blue.",
  "number one is a yellow lion",
  "number two is a brown giraffe",
  "number three is a gray cat",
  "number four is a blue fish",
  "number five is a yellow giraffe",
  "number six is a brown monkey",
  "number seven is a gray elephant",
  "number eight is a blue bird",
  "pets",
  "colors",
  "zoo animals",
  "blue",
  "cat",
  "dog",
  "elephant",
  "fish",
  "giraffe",
  "green",
  "orange",
  "monkey",
  "the elephant is blue",
  "the cat is yellow",
  "the fish is red",
  "the bird is green",
  "the monkey is black",
  "five blue fish",
  "three green monkeys",
  "two red elephants",
  "four brown and yellow giraffes",
  "it's a red trash can",
  "it's a gray elephant",
  "it's a black monkey",
  "it's a brown lion",
  "it's an orange box",
  "it is a red sharpener",
  "it isn't a green board",
  "this isn't a blue window",
  "it is a yellow pencil",
  "this isn't a gray eraser",
  "yes, it's a monkey",
  "no, it's a chair",
  "no, she's a teacher",
  "yes, she's a girl",
  "no, it's a lion",
  "what's this?|it's a table.",
  "what's this?|it's a teacher.",
  "what's the number? it's four.",
  "what color is it?|it's yellow.",
  "what's this?|it's a trash can.",
  "what's the number? it's one.",
  "what's this?|it's a boy.",
  "what color is it?|it's red.",
  "what's this?|it's an elephant.",
  "what's the number? it's five.",
  "what color is it?|it's orange.",
  "what's this?|it's a monkey.",
  "what color is it?|it's green.",
  "what color is it?|it's blue.",
  "what's this?|it's a lion.",
  "what's this?|it's a girl.",
  "what's the number? it's three."
];
  


