var unidad1 = [
  "Bella is a little brown bat with paper thin wings.",
"Stella is a little mouse with a long thin tail.",
"Bats and mice look a lot alike except that bats.",
"have wings and mice have tails.",
"Stella and Bella meet in the barn in the early morning.",
"They both like to sleep in a cozy place.",
"Bella flies up to the ceiling and grabs onto a beam with her back feet.",
"Then, hanging upside down, she wraps her wings around herself and goes to sleep.",
"Stella finds a soft pile of hay and goes to sleep.",
"with her tail curled around her.",
"Sweet dreams.",
"Everyone in Mrs. Smith's classroom is excited.",
"The class is going on a field trip to the local firehouse.",
"The children will see how everything in the firehouse is kept in tip top shape.",
"The firefighters' hats, coats and boots are lined up so they can be put on at a moment's notice.",
"The hoses and ladders are on the fire trucks.",
"Even Spot, the firehouse mascot, sits and waits for the alarm to sound.",
"If the children are very good, they might get to slide down the pole from the second floor.",
"Molly wanted to cheer up her mom, who was in bed with a cold.",
"She put a glass of milk and some cookies on a tray.",
"Then she covered the cookies with a big striped napkin and carried the tray to her mom's room.",
"Surprise, she said.",
"But just at that moment the cat jumped off the bed.",
"It bumped against Molly's leg, and the glass of milk turned over on the tray.",
"Molly said sadly, no.",
"But suddenly her mom burst out laughing.",
"Molly looked down and saw that the cat was busily lapping up some milk that had spilled on the floor.",
"Her mom winked and said, never cry over spilled milk.",
"Today we learned all about the Grand Canyon.",
"The canyon is more than two hundred miles long and up to six thousands feet deep.",
"If it were a building, it would be about six hundred stories high.",
"The Grand Canyon is called a gorge because its walls are so high and steep.",
"The Colorado River, which began forming the canyon millions of years ago, still rushes along the bottom.",
"People like to camp in the canyon and explore its beautiful scenery.",
"The Grand Canyon is in the state of Arizona.",
"Susie crawled into an old barrel in the backyard.",
"She was playing hide-and-seek with her cousins, and she thought she'd found a perfect hiding place.",
"After waiting a long time, Susie decided to get out and look around.",
"She wiggled and squirmed, but she was stuck in the barrel.",
"Finally, she called for help.",
"Soon everyone was looking down at her.",
"Well, joked Susie's older cousin, should we leave her here or pull her out?",
"Then, with one big tug, he lifted her out and gently set her down.",
"Be careful where you hide, he said, or we might never find you.",
"Our neighborhood is having a block party.",
"All the neighbors will come outdoors to visit with each other.",
"There will be lots of food to eat, games to play and music for dancing.",
"The firefighters from Station number tow will give children rides on their fire truck.",
"They will also open a fire hydrant and let the children play in the water.",
"Except for the fire truck, no traffic will be allowed on the block today.",
"People will be able to walk down the middle of the street.",
"New England is famous for its fall colors.",
"The leaves of trees turn beautiful shades of red, orange and yellow.",
"Apples ripen into rosy reds. Bright orange pumpkins dot the fields.",
"Families have pumpkin picking parties.",
"Then they carve the pumpkins into Halloween jack-o'-lanterns with funny faces.",
"When all the jack-o'-lanterns have been put in place, everyone enjoys a snack of doughnuts and apple cider.",
"Spring a ling a ding dong.",
"I sing a little spring song.",
"Winter's chased away.",
"Can't wait another day.",
"Here come the apple blossoms.",
"And the little baby possums.",
"The grass is turning green.",
"The yellow sun is often seen.",
"The flowers start to bloom.",
"Summer's coming soon.",
"Spring a ling-a ding dong.",
"I sing a little spring song.",
"Penny loves to play soccer.",
"She knows that practice is important if she wants to play well.",
"Penny practices kicking the ball.",
"She runs long distances.",
"She learns to share the ball with other players on her team.",
"And she works with her teammates on different ways to get the ball downfield to the opponent's goal.",
"Penny's team practices and plays all season.",
"Everyone on the team likes to win, even though it's more important to play well and be a good sport.",
"America is home to many animals.",
"There are rivers where catfish swim and otters play.",
"There are lakes for moose and busy beavers.",
"Birds glide on breezes that blow past squirrels in the treetops.",
"Mountain goats climb rocky peaks as eagles circle overhead.",
"Mighty buffalo roam with prairie dogs in open grasslands.",
"Turtles and frogs sun themselves on the edges of ponds while ducks paddle past.",
"We're lucky to have so many wild animals.",
"They help make America a wonderful place.",
"Steve took his dog Max for a walk.",
"Suddenly, Max sniffed at something beside the path, and Steve looked down.",
"There on the ground was a baby bird.",
"Steve wondered what he should do.",
"He looked around for help, but he and Max were alone with the baby bird.",
"Then he remembered that you should never pick up a creature that lives in the wild.",
"Come on, Max, he said.",
"Let's run home and ask Mom and Dad what to do.",
"Steve's parents called the wildlife association, and the little bird was saved.",
"Steve was glad he had done the right thing."
];

var maxUnidades = 1;
