var unidad1 = [
"Here we are in school again.",
"It's great to be with all my friends.",
"Hello and how are you?|I'm very well, thanks.|How about you?",
"Lots of fantastic things to do.",
"Reading, writing and playing too.",
"Lots of fantastic things to see.",
"I have all my friends with me.",
"What's your name?|I'm Rachel.",
"What's your favorite sport?|I like swimming.",
"Do you have pets?|Yes, I have a cat.",
"How old are you?|That's a secret.",
"I spy with my little eye.",
"I'm  watching something beginning with en.",
"Is it a nose?|No, it isn't.|Please guess again.",
"I spy with my little eye.",
"I'm  watching something beginning with c.",
"Is it chocolate?|Yes, it is.",
"Now spell the word with me.",
"How do you spell plane?",
"The TV is broken.",
"Is it five o'clock?No, it's three thirty.",
"What time is it?|It's four o'clock.",
"What time is it now?|It's four thirty.",
"Don't worry.|There's a lot of time.",
"It's five o'clock.|It's time for my favorite show.",
"Hurry up.|It's time for school.",
"Don't be late.",
"School is cool.",
"We love music and science.",
"So many things to learn and do.",
"I love math.",
"I like speaking spanish.",
"I love music.",
"Do you like math?|Yes, I love math.",
"Do you like speaking spanish?|Yes, I do.",
"Do you like music?|Yes, I do.",
"Do you like science?|Yes, I do.",
"Do you like art?|Yes, I do.",
"Hello, Dan.|What do you have today?|It's monday.|I have science.",
"Do you have music?|No, I don't.|I have music on friday.|Me too.",
"What do you have today, Olga?|I have english and science.",
"Do you have math?|Yes, at nine o'clock.|Look, it's nine o'clock now.",
"What do you have today?It's thursday.|I have math, english and art,",
"Hi, my name's Alice.",
"My favorite day is thursday.",
"In the morning, I have Spanish and music.",
"Math is my favorite subject.",
"I like playing games and writing stories on the computer.",
"In music class, I like playing the guitar.",
"In the afternoon, I have science.",
"I like studying plants and science class.",
"After school on Thursday, I go to the swimming club with my friends.",
"Thursday is a fantastic day.",
"Alice's favorite day is Tuesday.",
"Her favorite subject is math.",
"She has music in the afternoon.",
"She doesn't like playing the guitar.",
"She likes studying plants.",
"After school, she goes to tennis club.",
"It's nine thirty and Karim is late for school.|The principal isn't happy.",
"You have math now.|Hurry up.",
"The children aren't in the classroom.|Do we have science today?",
"Karim class isn't in the gym.|He doesn't have sport today?",
"Where is my class?|Look in the music room.",
"Karim is in the music room.",
"There are children playing and recording.",
"Where is my class?|Your class is in the library.",
"Karim is in the library.|There are a lots of books.",
"You have science now.|Go to the computer room.",
"Karim goes to the computer room.|But they aren't there.",
"I can't find my class.|Your class is on the playground.",
"It's time for the class photo.|Look at the big camera.",
"Karim shows the photo to his mom.|She doesn't like it.",
"Mom, here's the class photo.",
"Here's our classroom.|Can you see?",
"We're learning math.|My friends and mee.",
"In the gym we jump and climb.",
"We all have a fantastic time.",
"In the library, there are books.",
"Come with me and take a look.",
"The cafeteria is where we meet.",
"When it's time for us to eat.",
"My favorite subject is science.",
"The computer room's the place for me.",
"We go to the playground every day.|To see our friends and run and play.",
"You can't run or jump here.|You can read books.|Where am I?|You're in the library.",
"I'm Kate.|Look at the photos of the playground at my school.",
"We have a games area.|You can run and jump here.",
"This is the quiet area.|We read books and talk with our friends here.",
"We have a sports area.|You can play basketball, soccer and table tennis here.",
"This is our jungle gym.|Climbing's difficult for me, but I like it.",
"They are the new school librarians.",
"I have music next.|Can I have a songbook?",
"He is looking for songbooks.",
"This isn't the music section.",
"I have English homework today.",
"Follow me to the English section.",
"Do you have an English dictionary|Yes, they're on the top shelf.",
"Be quiet.|This is a library."];

var unidad2 = [
"Do you know the countries?",
"Sing along with me.",
"Can you find them on the map?",
"How many countries can you see?",
"Ireland, France and the United Kingdom.",
"And over there, is the United States of America.",
"Can you point to Mexico?",
"How many countries do you know?",
"China, Italy and Spain.",
"Let's sing the countries song.",
"How do you go to Mexico?",
"HI, my name is Karim.|Hello, I'm Tania.",
"Where are you from?|I'm from Italy.",
"Do you like skateboarding?|Yes, it's my favorite sport.",
"He's skateboarding with his hands.|He's fantastic.",
"Where's he from?|He's from the USA.",
"Look at that girl.|She's jumping.",
"That's Rosie.|She's from Ireland.|She's great.",
"Where are you from?|I'm from the UK.",
"How old are you ?|I'm nine.",
"Are you Laura?|Yes, I am.",
"Where are you from?|I'm from Mexico.",
"How old are you ?|I'm ten.",
"Are you Lucia?|No, I'm not.",
"My name is Nico.|I'm from Italy|I speak italian and english.",
"I'm Marta.|I'm from Spain.|I speak spanish and english.",
"My name is Jia.|I'm from China.|I speak chinese and english.",
"I'm Piere.|I'm from France.|I speak french and english.",
"Hello friends.|My name's Sam.|I'm nine years old.",
"I'm from the USA.|I speak english and spanish.",
"My hobbies are swimming and playing the guitar.",
"Please write to me.",
"Hi.|My name's Alicia.|I'm eight years old.",
"I'm from Mexico.|I speak english and spanish.",
"My hobbies are listening to music and writing to my friends.",
"Please write to me.",
"Lucy likes listening to music and dancing.",
"Her favorite singer is Paulina.|Paulina is from Mexico.|She's very smart.",
"She can speak spanish, english and french.",
"Paulina is singing on saturday.|Tom doesn't like Paulina.",
"Can we go to the concert, Dad?",
"Everybody likes Paulina.|There are no tickets left.",
"Sorry, Lucy.|We can't go to the concert.",
"Lucy is very sand.|She wants to go to the concert.",
"Look at that car.|That's Alberto.|He plays the guitar in Paulina's band.",
"Hello.|Can I help?Yes, please.",
"Pierre is from France.|He speaks french and spanish.|He doesn't speak english.",
"Dad helps fix the car.",
"Look, Lucy.|It's Paulina.|Hello.",
"Here are three tickets for my concert.|Thanks.",
"Now we can go to the concert.|Thank you.",
"And thank you to Lucy and Tom.",
"Paul is from France.|He likes painting and swimming at the sea.",
"Flor likes skiing and singing songs.|She's from Italy.",
"Ling is from China.|She likes cycling and reading comics.",
"Marco likes dancing.|He's from Spain.|What about you?",
"Tara is from Irelan.|She likes listening to music.",
"Roberto is from México.|He likes playing basketball.",
"Lorna is from UK.|She likes taking photos.",
"Mac is from the USA.|He likes surfing.",
"China is a big country in Asia.",
"The capital city is Beijing.",
"The chinese flag is red with five yellow stars.",
"Kites, firework and paper are chinese inventions.",
"Table tennis and gymnastics are popular sports in China.",
"Brazil is a big country, too.|It's in South America.",
"Brasilia is the capital city.",
"The brazilian flag is green, blue and yellow.",
"You can visit the Amazon rain forest in Brasil.",
"Jaguars and parrots live there.",
"Soccer and volleyball are popular sports in Brazil.",
"What's the capital city fo the USA?|It's Washington DC.",
"What's the capital of China?|It's Beijing.",
"What color is the spanish flag?|It's red and yellow.",
"What color is the french flag?|It's blue, white and red.",
"They are at an international food festival.",
"Come on.|I'm hungry.|Me too.",
"I love eating cheese.|Do you speak english?|Yes, I do.",
"This spaghetti is from Italy.|I don't like spaghetti.",
"What are these?|Be careful.|They're chilies.",
"He doesn't like chilies.",
"Here's some ice cream from Italy.|Thank you."];

var unidad3 = [
"January.",
"February.",
"March.",
"April.",
"May.",
"June.",
"July.",
"August.",
"September.",
"October.",
"November.",
"December.",
"The first three months of the year.",
"Sunny days are here.",
"Back to school with books and pens.",
"Another year begins again.",
"When's your birthday?|It's in February.",
"My birthday's in November.",
"Olga's cousin is visiting for Christmas.",
"His name's Ricky and he's from Australia.",
"Hi, Ricky.|Do you like Christmas?|Yes, I do.",
"In Australia it's hot and sunny on Christmas.",
"What do you wear on Christmas?|I wear shorts and a T-shirts.",
"I wear a sweater on Christmas.",
"What do you eat?|My family has a big barbecue.",
"I eat hot dogs and salad.",
"I don't eat salad on Christmas.",
"I eat turkey, vegetables and potatoes.",
"Where do you go?|I go to the beach with my family.",
"I swim in the ocean.",
"I want to go to Australia for Christmas.",
"It's fantastic.",
"What do you wear in January?|I wear a sweater and a coat.",
"What do you wear in july?|I wear shorts and T-shirts in the summer.",
"Where do you go in August?|We go to the beach with my family.",
"Where do you go in December?|We go ski resorts to play with snow.",
"What do you eat on Christmas?We eat roasted turkey and mashed potatoes.",
"What do you eat on June?|We eat fruits, such as strawberries, raspberries and blueberries.",
"In February we play with kites.",
"In July we go to the beach.",
"In October we celebrate hallowing.",
"In December we celebrate Christmas.",
"In January, I wear a T-shirt.",
"In February, I swim in the ocean.",
"In March, I go the the park.",
"In April, I ride my bike.",
"In May, I wear a sweater.",
"In June, I eat strawberries.",
"In July, I wear shorts.",
"In August, we go the beach.",
"In September, we go to school.",
"In November, I wear a hat.",
"In December, I eat ice cream.",
"In January, I don't wear a T-shirt.",
"In January, I wear a T-shirt in the gym.",
"Hi Mon.|It's winter here.|It's snowing.",
"It's very hot here today.|I don't like summer.",
"He is talking to his family in Australia on the computer.",
"It's summer in Australia.",
"The children are going ice-skating in the park.",
"I like your skates, Tom.",
"Ricky, don't forget your scarf.",
"Olga, don't forget the hot chocolate.",
"Tom wants to scare Ricky.",
"Look at the footprints.",
"It's a snow monster.",
"They are very big.",
"Be careful, Ricky.",
"Ice-skating is difficult.",
"Lucy and Olga are having fun.|But Karim doesn't like ice-skating.",
"Now, it's snowing.",
"Look, there's a shelter.|Let's go.",
"I don't like winter.|It's cold.",
"Where's the hot chocolate.|It's at home.",
"It's the snow monster.|Dat, it's you.",
"He's trying to scary him.",
"Let's have hot chocolate.",
"Tom is scared of snow monsters.",
"Seasons come, seasons go.",
"Some bring rain and some bring snow.",
"Some bring wind and some bring sun.",
"Which is your favorite one?",
"In the spring, there's a lot of rain.",
"All the flowers come out again.",
"In the summer, there's no school.",
"We go swimming in the pool.",
"In autumn, all the leaves fall down.",
"Red and yellow, orange and brown.",
"In winter, when the cold winds blow.",
"We go skiing in the snow.",
"I'm Tessa.|My favorite season is spring.",
"I like flowers and baby animals.",
"I wear a jacket and pants.",
"I ride my bike in the park.",
"I eat chocolate eggs at easter.",
"I'm Max.|My favorite season is autumn.",
"I like the red and yellow leaves.",
"I wear a hat and a coat.",
"I play soccer with my friends.",
"I eat grapes and apples.",
"In summer, it's hot and bears like swimming in cold rivers and lakes.",
"In Autumn, bears find a cave or make a den for winter.",
"They eat a lot and they grow more fur.",
"In winter, it's cold and brown bears sleep in a cave or in a den.",
"They don't eat or drink for three months.",
"Brown bears wake up in spring.",
"They are very hungry and eat a lot.",
"They eat plants, insects and fish.",
"Brown bears live in Spain, the USA, Russia and other countries.",
"In Spain, they are endangered species.",
"Brown bears stand on two legs to find food.",
"They are two meters tall.",
"Brown bears like to eat honey.",
"It's January and it's snowing.",
"I don't like the winter.",
"What is he doing?|Why is he painting the wall?",
"When it's summer, I go to the beach.",
"I wear shorts and sunglasses in summer.",
"He has tanning bed.",
"What are you doing?|it's a surprise.",
"It's very sunny in summer too.",
"Now, it's summer.|They are at the beach.",
"Thanks you.|I like your surprise."];

var unidad4 = [
"Shopping mall.",
"Museum.",
"Movie theater.",
"Park.",
"Hospital.",
"Zoo.",
"Swimming pool.",
"Train station.",
"My town is a wonderful place to be.",
"In my town, there's lots to see.",
"A shopping mall and a library.",
"There's a museum and a movie theater too.",
"There's a park and a hospital and a zoo.",
"There's a train station and a swimming pool.",
"I think my town is really cool.",
"So many things to see and do.",
"It's home for me and it's home for you.",
"Is there a swimming pool in your town?|Yes, there is.",
"Do you like swimming?|Yes, it's my favorite sport.",
"Is there a zoo?|No, there isn't, but there's a big park.",
"Is there a museum?|Yes, there is.",
"Is there a movie theater?|Yes, there is.",
"Is there a hospital?|No, there isn't.",
"Is there a bird?|Yes, there is.",
"Do you like movies?|Yes, I like superhero movies.|Me, too.",
"Let's go to the movie theater.",
"There isn't a library in Green Town.",
"There's a hospital in Yellow Town.",
"There's a movie theater in Blue Town.",
"There isn't a zoo in Green Town.",
"There's a train station in Yellow Town and Green Town.",
"There isn't a swimming pool in Green Town.",
"Do you live in a town?|No, I live in a village.",
"What should we do today?|I don't know.|I'm bored.",
"Dad is reading a newspaper.",
"Lucy and Tom don't want to watch TV.",
"Museum are boring.|Let's go swimming.",
"There's a new science museum.",
"I don't like swimming.",
"Hurry up.|This museum is really interesting.",
"Let's invite them.",
"Look at her hair.",
"Let's take a photo.",
"There's a robot spider behind you.",
"Olga is scared of spiders.|But Lucy likes the robots.",
"Lucy is flying.|It's magic.",
"The magnets help Lucy fly.",
"It's time to go now.|I don't want to go home.",
"Let's look at the robots again.",
"Lucy has a new T-shirt.",
"She thinks museums are fun now.",
"Let's go back to the museum tomorrow.",
"What should we do today?",
"Tell me, what should we do?",
"Let's go to the science museum.",
"You can come too.",
"What should we do today?",
"Tell me, what should we do?",
"Let's go to the swimming pool.",
"You can come too.",
"What should we do today?",
"Tell me, what should we do?",
"Let's go to the shopping mall.",
"You can come too.",
"It's raining.",
"It's bright and sunny.",
"It's snowing.",
"It's windy.",
"It's windy.|What should we do today?|Let's go to the park and fly a kite.",
"In my town, there's a bus station and a train station.",
"When it's raining, I go to school by bus.",
"When it's sunny, I walk to school.",
"This is my town.",
"There's a sports center and a swimming pool.",
"My favorite sport is gymnastics.",
"I do gymnastics with my friends at the sports center.",
"In June, there's a kite festival in my town.",
"I don't have a kite, but I like taking photos of kites.",
"My favorite place is the park.",
"I go to the park with my mom and dad on Sundays.",
"We ride our bikes and have picnic.",
"Come on, let's get on the bus.",
"There's a new movie at the movie theater.",
"They are at the bus station.",
"They are going to the sports center.",
"Where's him?|He isn't on the bus.",
"Wait for me.",
"He is running behind the bus, but the bus is fast.",
"He's lost.",
"Where's the sports center, please?|There's a sports center in the park.",
"He is waiting for her.",
"Let's go in, we're late.",
"Come on.|Running is good for you.",
"I'm tired.",
"He and she go to the zoo after school.",
"You can come too.|It's cool."];

var unidad5 = [
 "Eggs.",
"Ham.",
"Cereal.",
"Burger.",
"Salad.",
"Meat.",
"Rice.",
"Vegetables.",
"Soup.",
"Toast.",
"Are you hungry?|Yes, I am.|Me too.|Let's eat.",
"Let's all eat.",
"Come to the table and take a seat.",
"For breakfast there's cereal, eggs and ham.",
"And lots of toast with strawberry jam.",
"For lunch there's vegetables, burgers and rice.",
"All this food is very nice.",
"Soup and salad, fish and meat.",
"So many tasty things to eat.",
"What are your favorite kinds of food?|Ham, soup and salad.",
"How much is the soup?|It's four dollars and fifty cents.",
"How much is the salad?|It's three dollars and seventy five cents.",
"How much is the ham sandwich?|It's two dollars and ninety cents.",
"I have two dollars and ninety cents.",
"And I have five dollars.",
"The ham sandwich for you and the soup for me.",
"How much is the burger?|It's two dollars and eighty cents.",
"I have breakfast at eight o'clock.",
"I have cereal, milk and banana for breakfast.",
"I like reading comics in the morning.",
"I have lunch at one thirty.",
"I talk to my friends at lunch.",
"I have meat, vegetables and yogurt for lunch.",
"I have dinner at seven o'clock.",
"I have soup and toast for dinner.",
"I tell my sister stories.",
"What do you have for breakfast?",
"What do you have for lunch?",
"What do you have for dinner?",
"Welcome to the school fair.",
"Today is the school fair.",
"Karim and Tom are at the sandwich table.",
"Robert, the famous TV chef, is visiting the school.",
"Tom is making the sandwiches.",
"Can I have a cheese sandwich, please?|Here you are.",
"Later that day.",
"How much is that?|Three dollars and ninety cents.",
"Can I have a ham and salad sandwich, please?|There's no salad.",
"A ham and Jam sandwich.|That's one dollar and fifty cents.|Thank you.",
"The principal likes Tom's unusual sandwiches.",
"Here you are.",
"An egg and chocolate sandwich.",
"Thank you.|It's delicious.",
"These sandwiches are fantastic.",
"Look, there's a TV camera.",
"Two new star chefs, Tom and Karim.",
"Now you are famous TV chefs too.",
"Can I have an apple?",
"Can I have a cake?",
"Can I have a sandwich?",
"And a big milkshake?",
"Can I have a pizza?",
"With ham and cheese?",
"And can I have an ice cream?",
"Please.",
"Ham sandwich.",
"Cheese sandwich.",
"Egg sandwich.",
"Chicken sandwich.",
"A carton of orange juice.",
"A bottle of water.",
"A milkshake.",
"Can I have an egg sandwich and water, please?|Yes, that's two dollars and seventy cents.",
"Can I have a cheese sandwich and milkshake, please?",
"Can I have a ham sandwich and juice, please?",
"Can I have a chicken sandwich and bottle of water, please?",
"Chocolate, candy, soft and cake have a lot of sugar.|Eata little.",
"Cheese, milk, meat and fish contains proteins.",
"Proteins help children grow and be strong.",
"Eat two or three serving a day.",
"Fruit and vegetables come from plants.",
"Eat four or five servings a day.",
"They are having dinner in a restaurant.",
"Can I have fish soup and salad, please?",
"And can I have spaghetti and meatballs?",
"His meatball is falling on the floor.",
"His meatball is under the table.",
"His meatball is escaping.",
"Wait for me, meatball.",
"Can I have a sandwich?|With salad and ham?|And carrot and apple?|And strawberry jam?"];

var unidad6 = 
["Ant.",
"Ladybug.",
"Centipede.",
"Worm.",
"Bee.",
"Dragonfly.",
"Snail.",
"Grasshopper.",
"One dragonfly.",
"Two dragonflies.",
"Minibeasts are everywhere.",
"Look behind you.",
"Don't be scared.",
"In the garden, take a look.",
"Read about them in a book.",
"Dragonflies and ladybugs.",
"Living in the trees.",
"Grasshoppers and wriggly worms.",
"Butterflies and bees.",
"Ants and snails and centipedes.",
"Crawling through the grass.",
"Look and you can see them.",
"With your magnifying glass.",
"It's pink.|It can't fly.|The worm.",
"Bees are insects.",
"They are yellow and black.",
"They live in big colonies.",
"Wings.",
"Head.",
"Stinger.",
"Legs.",
"Antennae.",
"They have four wings.",
"They can fly.",
"They have two eyes and a mouth.",
"They don't have ears.",
"They have six legs.",
"They can walk.",
"They have two antennae.",
"They can smell flowers with their antennae.",
"They have a stinger.",
"Do snails have ears?|No, they don't.",
"Do ladybugs have wings?|Yes, they do.",
"Do grasshoppers have antennae?||Yes, they do.",
"Do ladybugs have six legs?|Yes, they do.",
"Do centipedes have stingers?|No, they don't.",
"Do worms have eyes?|No, they don't.",
"Do ants have antennae?|Yes, they do.",
"Do you like grasshoppers?|Yes, they're my favorite minibeasts.",
"How many legs do they have?|They have six legs.|They can jump and walk.",
"How many wings do they have?|They have four wings.|They can fly.",
"How many antennae do they have?|They have two antennae.",
"How many eyes do they have?|They have two big eyes.",
"Are grasshoppers your favorite minibeast too?|No, my favorite minibeasts are butterflies.",
"They have six legs and two small antennae.",
"Only queens and males have wings.",
"They don't have wings or legs.",
"They have a big shell.",
"They don't have wings.",
"They have two eyes and thirty legs.",
"They have two wings and six legs.",
"They have two small antennae.",
"Tom and Karim have art today.",
"They are making models.",
"Karim invents a new minibeast.",
"I like your model plane, Tom.",
"Later that day in the school garden.",
"Find interesting minibeasts and take photos.",
"Lucy and Olga have science.",
"They are doing a project on minibeasts.",
"Olga has a magnifying glass.",
"Olga is looking under a leaf.",
"Lucy is looking behind a tree.",
"There are lots of flowers.",
"Look at this.|What is it?|It's a ladybug.",
"Lucy is taking a photo.",
"Is it a dragonfly?|No, it is not a dragonfly.",
"How many wings do they have?|They have four wings.",
"Is it an insect?|I don't know.",
"The next day an expert visits the school.",
"Be careful.|Don't fall in the pond.",
"It's a giant Australian treefly.",
"They have five eyes, you know.",
"But giant Australian treeflies don't have eight legs.",
"That's my model minibeast.",
"Everyone likes Karim's model minibeast.",
"He wins a prize.",
"And the winner of the art competition is Karim.",
"Well done, Karim.",
"The garden is my favorite place.",
"I like to smell the flowers.",
"And watch the little minibeasts.",
"For hours and hours and hours.",
"There's a ladybug behind a leaf.",
"And spiders in the trees.",
"Frogs and goldfish in the pond.",
"And lots of ants and bees.",
"I like to sit down on the grass.",
"And look up at the sky.",
"I listen to the buzzing bees.",
"And watch the clouds go by.",
"Where's the fish?|It is in the pond.",
"Where's the snail?|It's behind the leaf.",
"Carnivores.|They eat other animals",
"Herbivores.|They eat plants, fruits and flowers.",
"Omnivores.|They eat other animals and plants.",
"Crocodiles, lions and dragonflies are carnivores.",
"Elephants, rabbits and caterpillars are herbivores.",
"Squirrels, ants and ladybugs are omnivores.",
"Food chain.",
"Ladybugs are omnivores.|They eat plants and other insects.",
"Dragonflies are carnivores.|They eat ladybugs, bees and mosquitoes.",
"Frogs eat dragonflies and other minibeasts.",
"Snakes eat frogs and small animals.",
"Eagles eat snakes, mammals and fish.",
"Omnivores eat animals and plants.",
"Rabbits are herbivores.",
"Dragonflies don't eat plants.",
"Snakes eat frogs and small animals.",
"They are having breakfast.",
"We don't have any honey.|Let's visit the bees.",
"The bees live in a hive.|They make honey.",
"Open the hive and take some honey.",
"I don't know.|Is this a good idea?",
"Now the bees are angry.|They don't like him taking the honey.",
"I don't like this.|They have stingers.",
"Don't worry.|They can't hurt you.",
"The bees are chasing him.|He's really scared now.",
"He jumps into the pond to escape the bees.",
"They are very angry now.",
"They can't sting you.|You are made of metal.",
"John and Ron near the pond.|Sitting on a log.",
"Don't put on your socks.|There's a frog.",
"Is there a movie theater in your town?",
"How much is the soup?",
"What do you have for breakfast?",
"Is there a museum in your town?",
"Name five minibeasts.",
"How much is the burger?",
"What do you have for dinner?",
"Where's the bee?",
"In my town there's a theater.",
"How many legs do spiders have?",
"Name six foods.",
"There isn't a swimming pool in Park Town.",
"There's a train station in New Town.",
"There's a park in New Town and Park Town.",
"There isn't a shopping mall in Park Town.",
"There's a zoo in New Town and Park Town.",
"There's a swimming pool in New Town.",
"How much is a burger and rice?|It's two dollars and twenty five cents.",
"They have wings and antennae.",
"They're big and green.",
"They can jump."];

var maxUnidades = 6;
