var unidad1 = [
"There are two eggs.",
"There are three toasts.",
"There is a glass of milk.",
"There is a glass of orange juice.",
"There are some bananas.",
"There is a bowl of cereal.",
"Are these bananas?|No, they aren't.",
"Is this orange juice?|Yes, it is.",
"Is this a toast?|No, it isn't.",
"Is this a bowl of cereal?|Yes, it is.",
"My name is Max and this is my family.",
"We are eating dinner.",
"I'm eating fish.",
"He's eating soup.",
"She's eating salad.",
"They're eating chicken.",
"He's my father.",
"She's my mother.",
"What's this?|It's chicken.",
"What's this?|It's salad.",
"What's this?|It's fish.",
"What's this?|It's soup.",
"She's eating salad.",
"He's eating soup.",
"She's eating fish.",
"He's eating chicken.",
"Is Anna eating toast?|Yes, she is.",
"Is Meg eating cereal?|No, she isn't.",
"Is Jack eating eggs?|Yes, he is.",
"Is Sam eating fish?|No, he isn't.",
"He's eating eggs.",
"She's drinking milk.",
"He's drinking orange juice.",
"She's eating soup.",
"One table.",
"Two. chairs.",
"Three balls.",
"Four oranges.",
"Five ducks.",
"Six books.",
"Seven erasers.",
"Eight eggs.",
"Nine pencils.",
"Ten bananas.",
"How many bananas are there?|There are two bananas.",
"How many boys are there?|There are four boys.",
"How many girls are there?|There are three girls.",
"How many pencils are there?|There is only one pencil.",
"How many books are there?|There are five books.",
"How many schoolbags are there?|There are seven schoolbags.",
"How many apples are there?|There are nine apples.",
"Time for breakfast.|Let's go eat.",
"Time for breakfast.|What a treat.",
"Cereal, eggs, bananas and toast.",
"What kind of breakfast food do you eat the most?",
"Time for dinner.|Let's go eat.",
"Time for dinner.|What a treat.",
"Salad, soup, chicken and fish.",
"What kind of dinner is on you dish?",
"Is she eating bananas?|Yes, she is.",
"Is he eating soup?|No, he isn't.",
"Is she drinking milk?|No, she isn't.",
"Is he eating eggs?|Yes, he is.",
"What do you eat for breakfast?|I eat eggs and toast.",
"What do you eat for dinner?|I eat chicken.",
"What do you eat for breakfast?|I eat fruits.",
"What do you eat for dinner?|I eat soup.",
"What do you eat for dinner?|I eat salad."
];

var unidad2 = [
"I eat pears.",
"She drinks yogurt.",
"He eats meat.",
"I love sandwiches.",
"I eat bread.",
"He eats jam.",
"She eats cheese.",
"I love peanut butter.",
"The pears are green.",
"The meat is white and red.",
"The peanut butter is in a box.",
"The yogurt is under the orange juice.",
"I want popcorn, please.",
"Where are the peanuts?|They're on the green plate.",
"Where's the popcorn?|It's in the red bowl.",
"Where are the raisins?|They're in the bag.",
"Where are the crackers?|They're in the blue bowl.",
"I want crackers, please.",
"I want raisins, please.",
"The meat is in the refrigerator.",
"The soup is on the table.",
"The apples are red.",
"The peanut butter is delicious.",
"The cheese is on the bread.",
"The salad is green and red.",
"The crackers are in the bowl.",
"The yogurt is pink.",
"The pears are green.",
"Is there salad in the bowl?",
"Is there soup in the bowl?",
"Is there yogurt on the plate?",
"The jam is red.",
"The peanut butter is on the table.",
"The meat is in the refrigerator.",
"The cheese is yellow.",
"The bread is toasted.",
"The crackers are in the bowl.",
"The yogurt is white.",
"The sandwich is delicious.",
"The jam is red.",
"The crackers are orange.",
"The meat is pink.",
"The yogurt is purple.",
"The cheese is yellow.",
"The bread is brown.",
"The peanut butter is brown.",
"The sandwich is yellow.",
"The monkey eats a banana.",
"The elephant eats peanuts.",
"The pigeon eats crackers.",
"The lion eats meat.",
"I want cheese and oranges, please.",
"I want raisine, plese.",
"The cheese is white.",
"The sandwich is on the plate.",
"The cheese is orange.",
"The peanut butter is on the table.",
"The jam is red.",
"The meat is in the box.",
"I want a salad.",
"The crackers are yellow.",
"The bread is under the table.",
"I want jam.",
"The banana is yellow.",
"The pears are in the box.",
"I want popcorn.",
"The soup is green.",
"The apples are in the schoolbag.",
"I want two eggs.",
"The meat is red.",
"Where's the apple?|It's on the plate.",
"Where is the popcorn?|It is in the pag.",
"Where are the crackers?|They're on the plate.",
"Where's the yogurt?|It's in the bowl.",
"Where are the raisins?|They're in the box.",
"Where are the peanuts?|They're in the bag.",
"What do you want?|I want popcorn, please.",
"What do you want?|I want yogurt, please.",
"What do you want?|I want peanuts, please.",
"What do you want?|I want raisins, please.",
"I want a banana, please.",
"I want a sandwich, please.",
"I want yogurt, please.",
"I want a salad, please.",
"I want oranges, please."
];

var unidad3 = [
"It's a school.",
"It's a supermarket.",
"It's a street.",
"They're bikes.",
"It's a bus.",
"They're cars.",
"They're taxis.",
"It's a park.",
"There are three bikes.",
"There are two taxis.",
"There are six cars.",
"There are five buses.",
"It's a blue bike.",
"It's a red car.",
"It's a yellow taxi.",
"It's a orange bus.",
"The yellow house is next to the orange house.",
"The purple house is in front of the light blue house.",
"The orange house is between the yellow house and the purple house.",
"The blue car is next to the green car.",
"The orange bus is in front of the red car.",
"The green car is between the orange bus and the blue car.",
"The yellow taxi is in front of the green car.",
"The purple car is next to the orange bus.",
"The blue car is in front of the red bus.",
"The yellow taxi is next to the red bus.",
"The red house.",
"The blue car.",
"The yellow bus.",
"Where are the bicycles?|They're in the park.",
"Where's the park?|It's between the supermarket and the yellow house.",
"Where's the school?|It's between the blue house and the purple house.",
"Where's the purple house?|It's next to the school.",
"The oranges are between the bananas and the eggs.",
"The green apples are in front of the eggs.",
"The pears are in front of the bananas.",
"The oranges are next to the bananas.",
"The red apples are between the green apples and the pears.",
"There are eleven green bikes on the table.",
"There are four blue bikes under the table.",
"How many bikes are there?|There are twelve bikes.",
"There is one red bus in the bag.",
"There are ten purple buses in the box.",
"How many buses are there?|There are five buses.",
"My father's running in the park.",
"He's having so much fun.",
"My brother's reading at the school.",
"My mother's walking down the street.",
"She's having so much fun.",
"Excuse me. Where's the school?|It's in front of you.",
"In front of me?|The school isn't in front of me.|The park is in front of me.",
"Excuse me. Where's the school?|It's next to the supermarket.",
"Next to the supermarket?|There's the supermarket.",
"Excuse me. Where's the school?|It's between the supermarket and the houses.",
"Good morning children.|I'm your new teacher.",
"The red house is between the park and the school.",
"The green house is in front of the school.",
"The supermarket is in front of the red house.",
"The blue house is next to the supermarket,",
"The blue house is in front of the park,",
"The school is next to the red house.",
"The supermarket is between the green house and the blue house.",
"The park is between the red house and the zoo.",
"How do you go to school?|I ride my bike."
];

var unidad4 = [
"The birds are flying.",
"The bear is walking.",
"The tigers are jumping.",
"The clown is juggling.",
"The big horses are white.",
"The clowns are in the car.",
"There are four small seals.",
"The monkeys are swinging.",
"What is the monkey doing? It is swinging.",
"The girl is taking pictures.",
"The monkey is swinging.",
"The bird is flying.",
"The boy is eating peanuts.",
"The clown is juggling.",
"She is taking pictures.",
"It is swinging.",
"They are flying.",
"He is eating peanuts.",
"He is juggling.",
"Is the horse jumping? Yes, it is.",
"Is the pigeon eating? No, it isn't.",
"Is the girl walking? No, she isn't.",
"Is the boy reading? Yes, he is.",
"Is the tiger running? No, it isn't.",
"Is the dog sleeping? Yes, it is.",
"He is buying some food.",
"She is drinking coffee.",
"They are feeding the animals.",
"He is swinging.",
"I am taking pictures.",
"It's a beautiful day at the zoo.",
"The zookeeper is feeding the seals.",
"The big monkey is swinging on the tree.",
"The tiger is sleeping.",
"The elephant is drinking water.",
"The girl is buying peanuts.",
"The boy is taking pictures of the elephant.",
"The bird is flying.",
"The bear is brown.",
"The girl is buying red apples.",
"The birds are flying.",
"The monkeys are jumping.",
"The giraffe is running.",
"The seal is gray.",
"The teacher is taking pictures.",
"The tiger is big.",
"This is a blue circle.",
"This is a green square.",
"This is a red rectangle.",
"This is a yellow triangle.",
"Shapes are here.|Shapes are there.",
"Shapes, shapes are everywhere.",
"A clock is a circle.",
"A window is a square.",
"A door is a rectangle.",
"Shapes are everywhere.",
"The small girl is watching a bear.",
"The bear is jumping.",
"The dog is barking.",
"The big girl is eating fruits.",
"The boy is buying popcorn.",
"What are you doing?|I'm watching tv.",
"What are you doing?|I'm eating a sandwich."
];
