var unidad1 = [
"There are two eggs.",
"There are three toasts.",
"There is a glass of milk.",
"There is a glass of orange juice.",
"There are some bananas.",
"There is a bowl of cereal.",
"Are these bananas?|No, they aren't.",
"Is this orange juice?|Yes, it is.",
"Is this a toast?|No, it isn't.",
"Is this a bowl of cereal?|Yes, it is.",
"My name is Max and this is my family.",
"We are eating dinner.",
"I'm eating fish.",
"He's eating soup.",
"She's eating salad.",
"They're eating chicken.",
"He's my father.",
"She's my mother.",
"What's this?|It's chicken.",
"What's this?|It's salad.",
"What's this?|It's fish.",
"What's this?|It's soup.",
"She's eating salad.",
"He's eating soup.",
"She's eating fish.",
"He's eating chicken.",
"Is Anna eating toast?|Yes, she is.",
"Is Meg eating cereal?|No, she isn't.",
"Is Jack eating eggs?|Yes, he is.",
"Is Sam eating fish?|No, he isn't.",
"He's eating eggs.",
"She's drinking milk.",
"He's drinking orange juice.",
"She's eating soup.",
"One table.",
"Two. chairs.",
"Three balls.",
"Four oranges.",
"Five ducks.",
"Six books.",
"Seven erasers.",
"Eight eggs.",
"Nine pencils.",
"Ten bananas.",
"How many bananas are there?|There are two bananas.",
"How many boys are there?|There are four boys.",
"How many girls are there?|There are three girls.",
"How many pencils are there?|There is only one pencil.",
"How many books are there?|There are five books.",
"How many schoolbags are there?|There are seven schoolbags.",
"How many apples are there?|There are nine apples.",
"Time for breakfast.|Let's go eat.",
"Time for breakfast.|What a treat.",
"Cereal, eggs, bananas and toast.",
"What kind of breakfast food do you eat the most?",
"Time for dinner.|Let's go eat.",
"Time for dinner.|What a treat.",
"Salad, soup, chicken and fish.",
"What kind of dinner is on you dish?",
"Is she eating bananas?|Yes, she is.",
"Is he eating soup?|No, he isn't.",
"Is she drinking milk?|No, she isn't.",
"Is he eating eggs?|Yes, he is.",
"What do you eat for breakfast?|I eat eggs and toast.",
"What do you eat for dinner?|I eat chicken.",
"What do you eat for breakfast?|I eat fruits.",
"What do you eat for dinner?|I eat soup.",
"What do you eat for dinner?|I eat salad."
];

var unidad2 = [
"I eat pears.",
"She drinks yogurt.",
"He eats meat.",
"I love sandwiches.",
"I eat bread.",
"He eats jam.",
"She eats cheese.",
"I love peanut butter.",
"The pears are green.",
"The meat is white and red.",
"The peanut butter is in a box.",
"The yogurt is under the orange juice.",
"I want popcorn, please.",
"Where are the peanuts?|They're on the green plate.",
"Where's the popcorn?|It's in the red bowl.",
"Where are the raisins?|They're in the bag.",
"Where are the crackers?|They're in the blue bowl.",
"I want crackers, please.",
"I want raisins, please.",
"The meat is in the refrigerator.",
"The soup is on the table.",
"The apples are red.",
"The peanut butter is delicious.",
"The cheese is on the bread.",
"The salad is green and red.",
"The crackers are in the bowl.",
"The yogurt is pink.",
"The pears are green.",
"Is there salad in the bowl?",
"Is there soup in the bowl?",
"Is there yogurt on the plate?",
"The jam is red.",
"The peanut butter is on the table.",
"The meat is in the refrigerator.",
"The cheese is yellow.",
"The bread is toasted.",
"The crackers are in the bowl.",
"The yogurt is white.",
"The sandwich is delicious.",
"The jam is red.",
"The crackers are orange.",
"The meat is pink.",
"The yogurt is purple.",
"The cheese is yellow.",
"The bread is brown.",
"The peanut butter is brown.",
"The sandwich is yellow.",
"The monkey eats a banana.",
"The elephant eats peanuts.",
"The pigeon eats crackers.",
"The lion eats meat.",
"I want cheese and oranges, please.",
"I want raisine, plese.",
"The cheese is white.",
"The sandwich is on the plate.",
"The cheese is orange.",
"The peanut butter is on the table.",
"The jam is red.",
"The meat is in the box.",
"I want a salad.",
"The crackers are yellow.",
"The bread is under the table.",
"I want jam.",
"The banana is yellow.",
"The pears are in the box.",
"I want popcorn.",
"The soup is green.",
"The apples are in the schoolbag.",
"I want two eggs.",
"The meat is red.",
"Where's the apple?|It's on the plate.",
"Where is the popcorn?|It is in the pag.",
"Where are the crackers?|They're on the plate.",
"Where's the yogurt?|It's in the bowl.",
"Where are the raisins?|They're in the box.",
"Where are the peanuts?|They're in the bag.",
"What do you want?|I want popcorn, please.",
"What do you want?|I want yogurt, please.",
"What do you want?|I want peanuts, please.",
"What do you want?|I want raisins, please.",
"I want a banana, please.",
"I want a sandwich, please.",
"I want yogurt, please.",
"I want a salad, please.",
"I want oranges, please."
]
