var unidad1 = ["Here we are in school again.",
"It's great to be with all my friends.",
"Hello and how are you?|I'm very well, thanks.|How about you?",
"Lots of fantastic things to do.",
"Reading, writing and playing too.",
"Lots of fantastic things to see.",
"I have all my friends with me.",
"What's your name?|I'm Rachel.",
"What's your favorite sport?|I like swimming.",
"Do you have pets?|Yes, I have a cat.",
"How old are you?|That's a secret.",
"I spy with my little eye.",
"I'm  watching something beginning with en.",
"Is it a nose?|No, it isn't.|Please guess again.",
"I spy with my little eye.",
"I'm  watching something beginning with c.",
"Is it chocolate?|Yes, it is.",
"Now spell the word with me.",
"How do you spell plane?",
"The TV is broken.",
"Is it five o'clock?No, it's three thirty.",
"What time is it?|It's four o'clock.",
"What time is it now?|It's four thirty.",
"Don't worry.|There's a lot of time.",
"It's five o'clock.|It's time for my favorite show.",
"Hurry up.|It's time for school.",
"Don't be late.",
"School is cool.",
"We love music and science.",
"So many things to learn and do.",
"I love math.",
"I like speaking spanish.",
"I love music.",
"Do you like math?|Yes, I love math.",
"Do you like speaking spanish?|Yes, I do.",
"Do you like music?|Yes, I do.",
"Do you like science?|Yes, I do.",
"Do you like art?|Yes, I do.",
"Hello, Dan.|What do you have today?|It's monday.|I have science.",
"Do you have music?|No, I don't.|I have music on friday.|Me too.",
"What do you have today, Olga?|I have english and science.",
"Do you have math?|Yes, at nine o'clock.|Look, it's nine o'clock now.",
"What do you have today?It's thursday.|I have math, english and art,",
"Hi, my name's Alice.",
"My favorite day is thursday.",
"In the morning, I have Spanish and music.",
"Math is my favorite subject.",
"I like playing games and writing stories on the computer.",
"In music class, I like playing the guitar.",
"In the afternoon, I have science.",
"I like studying plants and science class.",
"After school on Thursday, I go to the swimming club with my friends.",
"Thursday is a fantastic day.",
"Alice's favorite day is Tuesday.",
"Her favorite subject is math.",
"She has music in the afternoon.",
"She doesn't like playing the guitar.",
"She likes studying plants.",
"After school, she goes to tennis club.",
"It's nine thirty and Karim is late for school.|The principal isn't happy.",
"You have math now.|Hurry up.",
"The children aren't in the classroom.|Do we have science today?",
"Karim class isn't in the gym.|He doesn't have sport today?",
"Where is my class?|Look in the music room.",
"Karim is in the music room.",
"There are children playing and recording.",
"Where is my class?|Your class is in the library.",
"Karim is in the library.|There are a lots of books.",
"You have science now.|Go to the computer room.",
"Karim goes to the computer room.|But they aren't there.",
"I can't find my class.|Your class is on the playground.",
"It's time for the class photo.|Look at the big camera.",
"Karim shows the photo to his mom.|She doesn't like it.",
"Mom, here's the class photo.",
"Here's our classroom.|Can you see?",
"We're learning math.|My friends and mee.",
"In the gym we jump and climb.",
"We all have a fantastic time.",
"In the library, there are books.",
"Come with me and take a look.",
"The cafeteria is where we meet.",
"When it's time for us to eat.",
"My favorite subject is science.",
"The computer room's the place for me.",
"We go to the playground every day.|To see our friends and run and play.",
"You can't run or jump here.|You can read books.|Where am I?|You're in the library.",
"I'm Kate.|Look at the photos of the playground at my school.",
"We have a games area.|You can run and jump here.",
"This is the quiet area.|We read books and talk with our friends here.",
"We have a sports area.|You can play basketball, soccer and table tennis here.",
"This is our jungle gym.|Climbing's difficult for me, but I like it.",
"They are the new school librarians.",
"I have music next.|Can I have a songbook?",
"He is looking for songbooks.",
"This isn't the music section.",
"I have English homework today.",
"Follow me to the English section.",
"Do you have an English dictionary|Yes, they're on the top shelf.",
"Be quiet.|This is a library."];

var maxUnidades = 1;
